// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Tensorroot.Gov.Modules.Saude.Infrastructure.Persistence;

#nullable disable

namespace Tensorroot.Gov.Modules.Saude.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(SaudeDbContext))]
    [Migration("20260623130812_NavegabilidadePacienteBusca")]
    partial class NavegabilidadePacienteBusca
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("saude")
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Tensorroot.Gov.BuildingBlocks.Infrastructure.Auditing.AuditTrail", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("AffectedColumns")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EntityId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EntityName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("HashAnterior")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("HashAtual")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("IpAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NewValues")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OldValues")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("Sequencia")
                        .HasColumnType("bigint");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("TimestampUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "Sequencia");

                    b.HasIndex("TenantId", "TimestampUtc");

                    b.ToTable("AuditTrail", "saude");
                });

            modelBuilder.Entity("Tensorroot.Gov.Modules.Saude.Domain.Atendimento.Atendimento", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Ciap")
                        .HasMaxLength(4)
                        .HasColumnType("nvarchar(4)");

                    b.Property<string>("Cid")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int>("Competencia")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("DataHora")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("EstabelecimentoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Modalidade")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("NivelGarantia")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<Guid>("PacienteId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ProfissionalId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ProtocoloRnds")
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("Situacao")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "PacienteId");

                    b.ToTable("Atendimentos", "saude");
                });

            modelBuilder.Entity("Tensorroot.Gov.Modules.Saude.Domain.Fiscal.FundoMunicipalSaude", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Cnpj")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("nvarchar(14)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.ToTable("FundosMunicipaisSaude", "saude");
                });

            modelBuilder.Entity("Tensorroot.Gov.Modules.Saude.Domain.Fiscal.RegraClassificacaoAsps", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Efeito")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("FonteRecurso")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Funcao")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<string>("Subfuncao")
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateOnly>("VigenciaInicio")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "Funcao", "Subfuncao", "FonteRecurso", "VigenciaInicio");

                    b.ToTable("RegrasClassificacaoAsps", "saude");
                });

            modelBuilder.Entity("Tensorroot.Gov.Modules.Saude.Domain.Pacientes.Paciente", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Cns")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<bool>("CnsConfirmado")
                        .HasColumnType("bit");

                    b.Property<string>("CpfBusca")
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)");

                    b.Property<string>("Identificacao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Identificacao");

                    b.Property<string>("NomeBusca")
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("Situacao")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.ComplexProperty<Dictionary<string, object>>("Endereco", "Tensorroot.Gov.Modules.Saude.Domain.Pacientes.Paciente.Endereco#Endereco", b1 =>
                        {
                            b1.Property<string>("Bairro")
                                .IsRequired()
                                .HasMaxLength(120)
                                .HasColumnType("nvarchar(120)")
                                .HasColumnName("Bairro");

                            b1.Property<string>("Cep")
                                .IsRequired()
                                .HasMaxLength(8)
                                .HasColumnType("nvarchar(8)")
                                .HasColumnName("Cep");

                            b1.Property<string>("Logradouro")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("nvarchar(200)")
                                .HasColumnName("Logradouro");

                            b1.Property<string>("Municipio")
                                .IsRequired()
                                .HasMaxLength(120)
                                .HasColumnType("nvarchar(120)")
                                .HasColumnName("Municipio");

                            b1.Property<string>("Numero")
                                .IsRequired()
                                .HasMaxLength(30)
                                .HasColumnType("nvarchar(30)")
                                .HasColumnName("Numero");

                            b1.Property<string>("Uf")
                                .IsRequired()
                                .HasMaxLength(2)
                                .HasColumnType("nvarchar(2)")
                                .HasColumnName("Uf");
                        });

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "Cns")
                        .IsUnique();

                    b.HasIndex("TenantId", "CpfBusca");

                    b.HasIndex("TenantId", "NomeBusca");

                    b.ToTable("Pacientes", "saude");
                });

            modelBuilder.Entity("Tensorroot.Gov.Modules.Saude.Domain.Regulacao.SolicitacaoRegulacao", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateOnly?>("DataAutorizacao")
                        .HasColumnType("date");

                    b.Property<DateOnly>("DataSolicitacao")
                        .HasColumnType("date");

                    b.Property<Guid>("EstabelecimentoSolicitanteId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Justificativa")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<Guid>("PacienteId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Prioridade")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<Guid>("ProfissionalSolicitanteId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ProtocoloSisreg")
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("Situacao")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.ComplexProperty<Dictionary<string, object>>("Cota", "Tensorroot.Gov.Modules.Saude.Domain.Regulacao.SolicitacaoRegulacao.Cota#Cota", b1 =>
                        {
                            b1.Property<int>("Disponivel")
                                .HasColumnType("int")
                                .HasColumnName("CotaDisponivel");

                            b1.Property<int>("Total")
                                .HasColumnType("int")
                                .HasColumnName("CotaTotal");
                        });

                    b.ComplexProperty<Dictionary<string, object>>("Procedimento", "Tensorroot.Gov.Modules.Saude.Domain.Regulacao.SolicitacaoRegulacao.Procedimento#Procedimento", b1 =>
                        {
                            b1.Property<string>("CodigoSigtap")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("nvarchar(20)")
                                .HasColumnName("ProcedimentoCodigoSigtap");

                            b1.Property<string>("Descricao")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("nvarchar(200)")
                                .HasColumnName("ProcedimentoDescricao");
                        });

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "PacienteId");

                    b.HasIndex("TenantId", "Situacao");

                    b.ToTable("SolicitacoesRegulacao", "saude");
                });

            modelBuilder.Entity("Tensorroot.Gov.Modules.Saude.Infrastructure.Fiscal.LinhaExecucaoSaude", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Exercicio")
                        .HasColumnType("int");

                    b.Property<string>("FonteRecurso")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Funcao")
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<string>("OrigemHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("Subfuncao")
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<decimal>("Valor")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "Exercicio");

                    b.HasIndex("TenantId", "OrigemHash")
                        .IsUnique();

                    b.ToTable("LinhasExecucaoSaude", "saude");
                });

            modelBuilder.Entity("Tensorroot.Gov.Modules.Saude.Infrastructure.Fiscal.ParametroFiscalSaude", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Chave")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Valor")
                        .HasColumnType("decimal(18,6)");

                    b.Property<DateOnly>("VigenciaInicio")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "Chave", "VigenciaInicio")
                        .IsUnique();

                    b.ToTable("ParametrosFiscaisSaude", "saude");
                });

            modelBuilder.Entity("Tensorroot.Gov.SharedKernel.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("int");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DeadLetteredOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Error")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("NextAttemptUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("OccurredOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ProcessedOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("ProcessedOnUtc", "DeadLetteredOnUtc", "NextAttemptUtc");

                    b.ToTable("OutboxMessages", "saude");
                });

            modelBuilder.Entity("Tensorroot.Gov.Modules.Saude.Domain.Atendimento.Atendimento", b =>
                {
                    b.OwnsOne("Tensorroot.Gov.Modules.Saude.Domain.Atendimento.AssinaturaDigital", "Assinatura", b1 =>
                        {
                            b1.Property<Guid>("AtendimentoId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<DateTimeOffset>("Carimbo")
                                .HasColumnType("datetimeoffset")
                                .HasColumnName("AssinaturaCarimbo");

                            b1.Property<string>("CertificadoIcpBrasil")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("nvarchar(200)")
                                .HasColumnName("AssinaturaCertificado");

                            b1.Property<string>("Hash")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("nvarchar(200)")
                                .HasColumnName("AssinaturaHash");

                            b1.Property<string>("Nivel")
                                .IsRequired()
                                .HasMaxLength(10)
                                .HasColumnType("nvarchar(10)")
                                .HasColumnName("AssinaturaNivel");

                            b1.HasKey("AtendimentoId");

                            b1.ToTable("Atendimentos", "saude");

                            b1.WithOwner()
                                .HasForeignKey("AtendimentoId");
                        });

                    b.OwnsMany("Tensorroot.Gov.Modules.Saude.Domain.Atendimento.EvolucaoSOAP", "Evolucoes", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<bool>("Assinada")
                                .HasColumnType("bit");

                            b1.Property<Guid>("AtendimentoId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Avaliacao")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<DateTimeOffset>("DataHora")
                                .HasColumnType("datetimeoffset");

                            b1.Property<bool>("EhAdendo")
                                .HasColumnType("bit");

                            b1.Property<Guid?>("EvolucaoReferenciadaId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Objetivo")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Plano")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Subjetivo")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("Id");

                            b1.HasIndex("AtendimentoId");

                            b1.ToTable("AtendimentosEvolucoes", "saude");

                            b1.WithOwner()
                                .HasForeignKey("AtendimentoId");
                        });

                    b.OwnsMany("Tensorroot.Gov.Modules.Saude.Domain.Atendimento.Prescricao", "Prescricoes", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<Guid>("AtendimentoId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<DateTimeOffset>("DataHora")
                                .HasColumnType("datetimeoffset");

                            b1.Property<string>("Item")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("nvarchar(200)");

                            b1.Property<string>("Posologia")
                                .IsRequired()
                                .HasMaxLength(500)
                                .HasColumnType("nvarchar(500)");

                            b1.HasKey("Id");

                            b1.HasIndex("AtendimentoId");

                            b1.ToTable("AtendimentosPrescricoes", "saude");

                            b1.WithOwner()
                                .HasForeignKey("AtendimentoId");
                        });

                    b.OwnsMany("Tensorroot.Gov.Modules.Saude.Domain.Atendimento.SolicitacaoExame", "SolicitacoesExame", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<Guid>("AtendimentoId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<DateTimeOffset>("DataHora")
                                .HasColumnType("datetimeoffset");

                            b1.Property<string>("Justificativa")
                                .IsRequired()
                                .HasMaxLength(500)
                                .HasColumnType("nvarchar(500)");

                            b1.Property<string>("Procedimento")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("nvarchar(200)");

                            b1.HasKey("Id");

                            b1.HasIndex("AtendimentoId");

                            b1.ToTable("AtendimentosSolicitacoesExame", "saude");

                            b1.WithOwner()
                                .HasForeignKey("AtendimentoId");
                        });

                    b.Navigation("Assinatura");

                    b.Navigation("Evolucoes");

                    b.Navigation("Prescricoes");

                    b.Navigation("SolicitacoesExame");
                });

            modelBuilder.Entity("Tensorroot.Gov.Modules.Saude.Domain.Fiscal.FundoMunicipalSaude", b =>
                {
                    b.OwnsMany("Tensorroot.Gov.Modules.Saude.Domain.Fiscal.ContaBlocoFinanciamento", "Contas", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Bloco")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("nvarchar(20)");

                            b1.Property<string>("FonteRecurso")
                                .IsRequired()
                                .HasMaxLength(10)
                                .HasColumnType("nvarchar(10)");

                            b1.Property<Guid>("FundoId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<decimal>("TotalExecutado")
                                .HasColumnType("decimal(18,2)");

                            b1.Property<decimal>("TotalRecebido")
                                .HasColumnType("decimal(18,2)");

                            b1.HasKey("Id");

                            b1.HasIndex("FundoId", "Bloco", "FonteRecurso")
                                .IsUnique();

                            b1.ToTable("ContasBlocoFinanciamentoSaude", "saude");

                            b1.WithOwner()
                                .HasForeignKey("FundoId");
                        });

                    b.Navigation("Contas");
                });

            modelBuilder.Entity("Tensorroot.Gov.Modules.Saude.Domain.Pacientes.Paciente", b =>
                {
                    b.OwnsMany("Tensorroot.Gov.Modules.Saude.Domain.Pacientes.Alergia", "Alergias", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<DateOnly>("DataRegistro")
                                .HasColumnType("date");

                            b1.Property<string>("Gravidade")
                                .IsRequired()
                                .HasMaxLength(40)
                                .HasColumnType("nvarchar(40)");

                            b1.Property<Guid>("PacienteId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Substancia")
                                .IsRequired()
                                .HasMaxLength(120)
                                .HasColumnType("nvarchar(120)");

                            b1.HasKey("Id");

                            b1.HasIndex("PacienteId");

                            b1.ToTable("PacientesAlergias", "saude");

                            b1.WithOwner()
                                .HasForeignKey("PacienteId");
                        });

                    b.OwnsMany("Tensorroot.Gov.Modules.Saude.Domain.Pacientes.CondicaoDeSaude", "Condicoes", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<bool>("Ativa")
                                .HasColumnType("bit");

                            b1.Property<string>("Codigo")
                                .IsRequired()
                                .HasMaxLength(10)
                                .HasColumnType("nvarchar(10)");

                            b1.Property<DateOnly>("DataRegistro")
                                .HasColumnType("date");

                            b1.Property<string>("Descricao")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("nvarchar(200)");

                            b1.Property<Guid>("PacienteId")
                                .HasColumnType("uniqueidentifier");

                            b1.HasKey("Id");

                            b1.HasIndex("PacienteId");

                            b1.ToTable("PacientesCondicoes", "saude");

                            b1.WithOwner()
                                .HasForeignKey("PacienteId");
                        });

                    b.Navigation("Alergias");

                    b.Navigation("Condicoes");
                });
#pragma warning restore 612, 618
        }
    }
}
