// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Tensorroot.Gov.Modules.Financas.Infrastructure.Persistence;

#nullable disable

namespace Tensorroot.Gov.Modules.Financas.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(FinancasDbContext))]
    [Migration("20260622132355_Inicial")]
    partial class Inicial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("financas")
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Tensorroot.Gov.BuildingBlocks.Infrastructure.Auditing.AuditTrail", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("AffectedColumns")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EntityId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EntityName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("IpAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NewValues")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OldValues")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("TimestampUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "TimestampUtc");

                    b.ToTable("AuditTrail", "financas");
                });

            modelBuilder.Entity("Tensorroot.Gov.Modules.Financas.Domain.Dotacoes.DotacaoOrcamentaria", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Exercicio")
                        .HasColumnType("int");

                    b.Property<string>("Situacao")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("ValorAnulado")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ValorDotadoInicial")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ValorEmpenhadoLiquido")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ValorReforcado")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "Exercicio");

                    b.ToTable("Dotacoes", "financas");
                });

            modelBuilder.Entity("Tensorroot.Gov.Modules.Financas.Domain.Empenhos.Empenho", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateOnly>("DataEmpenho")
                        .HasColumnType("date");

                    b.Property<Guid>("DotacaoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Exercicio")
                        .HasColumnType("int");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Situacao")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<decimal>("ValorAnulado")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ValorEmpenhado")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ValorLiquidado")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ValorPago")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("DotacaoId");

                    b.HasIndex("TenantId", "Exercicio", "Numero")
                        .IsUnique();

                    b.ToTable("Empenhos", "financas");
                });

            modelBuilder.Entity("Tensorroot.Gov.Modules.Financas.Domain.Liquidacoes.Liquidacao", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateOnly>("DataLiquidacao")
                        .HasColumnType("date");

                    b.Property<Guid>("EmpenhoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Situacao")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Valor")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ValorPago")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("EmpenhoId");

                    b.HasIndex("TenantId", "EmpenhoId");

                    b.ToTable("Liquidacoes", "financas");
                });

            modelBuilder.Entity("Tensorroot.Gov.Modules.Financas.Domain.Pagamentos.OrdemDePagamento", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateOnly>("DataPagamento")
                        .HasColumnType("date");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Situacao")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("ValorTotal")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "Numero")
                        .IsUnique();

                    b.ToTable("OrdensDePagamento", "financas");
                });

            modelBuilder.Entity("Tensorroot.Gov.Modules.Financas.Domain.Receitas.ReceitaArrecadada", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateOnly>("Data")
                        .HasColumnType("date");

                    b.Property<Guid>("OrigemId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Valor")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "OrigemId");

                    b.ToTable("ReceitasArrecadadas", "financas");
                });

            modelBuilder.Entity("Tensorroot.Gov.Modules.Financas.Domain.RestosAPagar.RestoAPagar", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Classificacao")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<Guid>("EmpenhoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ExercicioInscricao")
                        .HasColumnType("int");

                    b.Property<int>("ExercicioOrigem")
                        .HasColumnType("int");

                    b.Property<string>("Situacao")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("ValorCancelado")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ValorInscrito")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ValorLiquidado")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ValorPago")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("EmpenhoId");

                    b.HasIndex("TenantId", "ExercicioInscricao");

                    b.ToTable("RestosAPagar", "financas");
                });

            modelBuilder.Entity("Tensorroot.Gov.SharedKernel.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Error")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("OccurredOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ProcessedOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("ProcessedOnUtc");

                    b.ToTable("OutboxMessages", "financas");
                });

            modelBuilder.Entity("Tensorroot.Gov.Modules.Financas.Domain.Dotacoes.DotacaoOrcamentaria", b =>
                {
                    b.OwnsOne("Tensorroot.Gov.Modules.Financas.Domain.ValueObjects.ClassificacaoOrcamentaria", "Classificacao", b1 =>
                        {
                            b1.Property<Guid>("DotacaoOrcamentariaId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("CategoriaEconomica")
                                .IsRequired()
                                .HasMaxLength(30)
                                .HasColumnType("nvarchar(30)")
                                .HasColumnName("CategoriaEconomica");

                            b1.Property<string>("FonteDeRecurso")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("nvarchar(20)")
                                .HasColumnName("FonteDeRecurso");

                            b1.Property<string>("FuncionalProgramatica")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("nvarchar(50)")
                                .HasColumnName("FuncionalProgramatica");

                            b1.Property<string>("Orgao")
                                .IsRequired()
                                .HasMaxLength(10)
                                .HasColumnType("nvarchar(10)")
                                .HasColumnName("Orgao");

                            b1.Property<string>("UnidadeOrcamentaria")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("nvarchar(20)")
                                .HasColumnName("UnidadeOrcamentaria");

                            b1.HasKey("DotacaoOrcamentariaId");

                            b1.ToTable("Dotacoes", "financas");

                            b1.WithOwner()
                                .HasForeignKey("DotacaoOrcamentariaId");
                        });

                    b.Navigation("Classificacao")
                        .IsRequired();
                });

            modelBuilder.Entity("Tensorroot.Gov.Modules.Financas.Domain.Empenhos.Empenho", b =>
                {
                    b.OwnsOne("Tensorroot.Gov.Modules.Financas.Domain.ValueObjects.Credor", "Credor", b1 =>
                        {
                            b1.Property<Guid>("EmpenhoId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Documento")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("nvarchar(20)")
                                .HasColumnName("CredorDocumento");

                            b1.Property<string>("Nome")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("nvarchar(200)")
                                .HasColumnName("CredorNome");

                            b1.Property<string>("Tipo")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("nvarchar(20)")
                                .HasColumnName("CredorTipo");

                            b1.HasKey("EmpenhoId");

                            b1.ToTable("Empenhos", "financas");

                            b1.WithOwner()
                                .HasForeignKey("EmpenhoId");
                        });

                    b.Navigation("Credor")
                        .IsRequired();
                });

            modelBuilder.Entity("Tensorroot.Gov.Modules.Financas.Domain.Liquidacoes.Liquidacao", b =>
                {
                    b.OwnsOne("Tensorroot.Gov.Modules.Financas.Domain.ValueObjects.DocumentoComprobatorio", "Documento", b1 =>
                        {
                            b1.Property<Guid>("LiquidacaoId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("ChaveAcessoNfse")
                                .HasMaxLength(44)
                                .HasColumnType("nvarchar(44)")
                                .HasColumnName("DocumentoChaveNfse");

                            b1.Property<DateOnly?>("DataEmissao")
                                .HasColumnType("date")
                                .HasColumnName("DocumentoDataEmissao");

                            b1.Property<string>("Numero")
                                .HasMaxLength(60)
                                .HasColumnType("nvarchar(60)")
                                .HasColumnName("DocumentoNumero");

                            b1.Property<string>("Tipo")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("nvarchar(20)")
                                .HasColumnName("DocumentoTipo");

                            b1.HasKey("LiquidacaoId");

                            b1.ToTable("Liquidacoes", "financas");

                            b1.WithOwner()
                                .HasForeignKey("LiquidacaoId");
                        });

                    b.Navigation("Documento")
                        .IsRequired();
                });

            modelBuilder.Entity("Tensorroot.Gov.Modules.Financas.Domain.Pagamentos.OrdemDePagamento", b =>
                {
                    b.OwnsMany("Tensorroot.Gov.Modules.Financas.Domain.Pagamentos.ItemPagamento", "Itens", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<Guid>("LiquidacaoId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<Guid>("OrdemDePagamentoId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<decimal>("Valor")
                                .HasColumnType("decimal(18,2)");

                            b1.HasKey("Id");

                            b1.HasIndex("LiquidacaoId");

                            b1.HasIndex("OrdemDePagamentoId");

                            b1.ToTable("ItensPagamento", "financas");

                            b1.WithOwner()
                                .HasForeignKey("OrdemDePagamentoId");
                        });

                    b.OwnsOne("Tensorroot.Gov.Modules.Financas.Domain.ValueObjects.ContaBancaria", "ContaBancaria", b1 =>
                        {
                            b1.Property<Guid>("OrdemDePagamentoId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Agencia")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("nvarchar(20)")
                                .HasColumnName("ContaAgencia");

                            b1.Property<string>("Banco")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("nvarchar(20)")
                                .HasColumnName("ContaBanco");

                            b1.Property<string>("Conta")
                                .IsRequired()
                                .HasMaxLength(30)
                                .HasColumnType("nvarchar(30)")
                                .HasColumnName("ContaNumero");

                            b1.Property<string>("Pix")
                                .HasMaxLength(140)
                                .HasColumnType("nvarchar(140)")
                                .HasColumnName("ContaPix");

                            b1.HasKey("OrdemDePagamentoId");

                            b1.ToTable("OrdensDePagamento", "financas");

                            b1.WithOwner()
                                .HasForeignKey("OrdemDePagamentoId");
                        });

                    b.Navigation("ContaBancaria")
                        .IsRequired();

                    b.Navigation("Itens");
                });
#pragma warning restore 612, 618
        }
    }
}
