// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Tensorroot.Gov.Modules.Financas.Infrastructure.Persistence;

#nullable disable

namespace Tensorroot.Gov.Modules.Financas.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(FinancasDbContext))]
    partial class FinancasDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("financas")
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Tensorroot.Gov.BuildingBlocks.Infrastructure.Auditing.AuditTrail", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("AffectedColumns")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EntityId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EntityName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("HashAnterior")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("HashAtual")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("IpAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NewValues")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OldValues")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("Sequencia")
                        .HasColumnType("bigint");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("TimestampUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "Sequencia")
                        .IsUnique()
                        .HasFilter("[Sequencia] > 0");

                    b.HasIndex("TenantId", "TimestampUtc");

                    b.ToTable("AuditTrail", "financas");
                });

            modelBuilder.Entity("Tensorroot.Gov.Modules.Financas.Application.Contabilidade.ReadModels.LinhaBalancete", b =>
                {
                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ContaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Exercicio")
                        .HasColumnType("int");

                    b.Property<int>("PeriodoMes")
                        .HasColumnType("int");

                    b.Property<string>("CodigoConta")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("NaturezaInformacao")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("NaturezaSaldo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("Nivel")
                        .HasColumnType("int");

                    b.Property<decimal>("SaldoAnterior")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("SaldoAtual")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal>("TotalCreditos")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalDebitos")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("TenantId", "ContaId", "Exercicio", "PeriodoMes");

                    b.HasIndex("TenantId", "Exercicio", "PeriodoMes");

                    b.ToTable("balancete_conta", "financas");
                });

            modelBuilder.Entity("Tensorroot.Gov.Modules.Financas.Application.Contabilidade.ReadModels.MscGeradaRegistro", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Exercicio")
                        .HasColumnType("int");

                    b.Property<DateTime>("GeradaEmUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("Mes")
                        .HasColumnType("int");

                    b.Property<int>("QuantidadeLinhas")
                        .HasColumnType("int");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("TipoMatriz")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "Exercicio", "Mes", "TipoMatriz")
                        .IsUnique();

                    b.ToTable("msc_gerada", "financas");
                });

            modelBuilder.Entity("Tensorroot.Gov.Modules.Financas.Domain.Contabilidade.Encerramento.EncerramentoExercicio", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("AberturaConcluidaEmUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("EncerradoEmUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("Exercicio")
                        .HasColumnType("int");

                    b.Property<DateTime>("IniciadoEmUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "Exercicio")
                        .IsUnique();

                    b.ToTable("encerramento_exercicio", "financas");
                });

            modelBuilder.Entity("Tensorroot.Gov.Modules.Financas.Domain.Contabilidade.EventosContabeis.EventoContabil", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<int?>("ExercicioVigenciaFim")
                        .HasColumnType("int");

                    b.Property<int>("ExercicioVigenciaInicio")
                        .HasColumnType("int");

                    b.Property<string>("Fato")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "Fato", "ExercicioVigenciaInicio");

                    b.ToTable("EventosContabeis", "financas");
                });

            modelBuilder.Entity("Tensorroot.Gov.Modules.Financas.Domain.Contabilidade.Lancamentos.LancamentoContabil", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateOnly>("Data")
                        .HasColumnType("date");

                    b.Property<bool>("Estornado")
                        .HasColumnType("bit");

                    b.Property<Guid?>("EventoContabilId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Exercicio")
                        .HasColumnType("int");

                    b.Property<string>("Historico")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<Guid?>("LancamentoEstornoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("NaturezaInformacao")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Origem")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<Guid?>("OrigemReferenciaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("PeriodoMes")
                        .HasColumnType("int");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "Exercicio", "PeriodoMes");

                    b.HasIndex("TenantId", "OrigemReferenciaId", "EventoContabilId");

                    b.ToTable("LancamentosContabeis", "financas");
                });

            modelBuilder.Entity("Tensorroot.Gov.Modules.Financas.Domain.Contabilidade.PlanoDeContas.ContaContabil", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Ativa")
                        .HasColumnType("bit");

                    b.Property<int>("Classe")
                        .HasColumnType("int");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("Codigo");

                    b.Property<Guid?>("ContaPaiId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Encerramento")
                        .HasColumnType("bit");

                    b.Property<string>("Funcao")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Funcionamento")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("IndicadorSuperavitFinanceiro")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("NaturezaInformacao")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("NaturezaSaldo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("Nivel")
                        .HasColumnType("int");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "Codigo")
                        .IsUnique();

                    b.ToTable("ContasContabeis", "financas");
                });

            modelBuilder.Entity("Tensorroot.Gov.Modules.Financas.Domain.Credores.CredorCadastrado", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Documento")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Situacao")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "Documento")
                        .IsUnique();

                    b.HasIndex("TenantId", "Nome");

                    b.ToTable("Credores", "financas");
                });

            modelBuilder.Entity("Tensorroot.Gov.Modules.Financas.Domain.Dotacoes.DotacaoOrcamentaria", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("AcaoPpaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Exercicio")
                        .HasColumnType("int");

                    b.Property<Guid?>("ItemDespesaFixadaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("LoaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Situacao")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("ValorAnulado")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ValorDotadoInicial")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ValorEmpenhadoLiquido")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ValorReforcado")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "Exercicio");

                    b.ToTable("Dotacoes", "financas");
                });

            modelBuilder.Entity("Tensorroot.Gov.Modules.Financas.Domain.Empenhos.Empenho", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateOnly>("DataEmpenho")
                        .HasColumnType("date");

                    b.Property<Guid>("DotacaoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Exercicio")
                        .HasColumnType("int");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Situacao")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<decimal>("ValorAnulado")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ValorEmpenhado")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ValorLiquidado")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ValorPago")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("DotacaoId");

                    b.HasIndex("TenantId", "Exercicio", "Numero")
                        .IsUnique();

                    b.ToTable("Empenhos", "financas");
                });

            modelBuilder.Entity("Tensorroot.Gov.Modules.Financas.Domain.Liquidacoes.Liquidacao", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateOnly>("DataLiquidacao")
                        .HasColumnType("date");

                    b.Property<Guid>("EmpenhoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Situacao")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Valor")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ValorPago")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("EmpenhoId");

                    b.HasIndex("TenantId", "EmpenhoId");

                    b.ToTable("Liquidacoes", "financas");
                });

            modelBuilder.Entity("Tensorroot.Gov.Modules.Financas.Domain.Pagamentos.OrdemDePagamento", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateOnly>("DataPagamento")
                        .HasColumnType("date");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Situacao")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("ValorTotal")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "Numero")
                        .IsUnique();

                    b.ToTable("OrdensDePagamento", "financas");
                });

            modelBuilder.Entity("Tensorroot.Gov.Modules.Financas.Domain.Planejamento.Creditos.CreditoAdicional", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AtoAbertura")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("AtoAutorizador")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid?>("DotacaoAlvoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("DotacaoAnuladaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Especie")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("Exercicio")
                        .HasColumnType("int");

                    b.Property<string>("Fonte")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<Guid>("LoaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("PorDecreto")
                        .HasColumnType("bit");

                    b.Property<string>("Situacao")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Valor")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "LoaId");

                    b.ToTable("CreditosAdicionais", "financas");
                });

            modelBuilder.Entity("Tensorroot.Gov.Modules.Financas.Domain.Planejamento.Ldo.AnexoLdo", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("LdoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Obrigatorio")
                        .HasColumnType("bit");

                    b.Property<string>("ReferenciaDocumento")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.HasIndex("LdoId");

                    b.ToTable("LdoAnexos", "financas");
                });

            modelBuilder.Entity("Tensorroot.Gov.Modules.Financas.Domain.Planejamento.Ldo.LeiDiretrizes", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AnoLei")
                        .HasColumnType("int");

                    b.Property<int>("Exercicio")
                        .HasColumnType("int");

                    b.Property<string>("NumeroLei")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<Guid>("PpaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Situacao")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "Exercicio");

                    b.ToTable("LeisDiretrizes", "financas");
                });

            modelBuilder.Entity("Tensorroot.Gov.Modules.Financas.Domain.Planejamento.Ldo.MetaFiscal", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Ano")
                        .HasColumnType("int");

                    b.Property<decimal>("DespesaTotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("DividaConsolidada")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("LdoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("ReceitaTotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ResultadoNominal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ResultadoPrimario")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("LdoId");

                    b.ToTable("LdoMetasFiscais", "financas");
                });

            modelBuilder.Entity("Tensorroot.Gov.Modules.Financas.Domain.Planejamento.Ldo.PrioridadeLdo", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AcaoPpaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Justificativa")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<Guid>("LdoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Ordem")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("LdoId");

                    b.ToTable("LdoPrioridades", "financas");
                });

            modelBuilder.Entity("Tensorroot.Gov.Modules.Financas.Domain.Planejamento.Loa.ItemDespesaFixada", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AcaoPpaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("DotacaoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("LoaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("NaturezaDespesa")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<bool>("OrigemCreditoEspecial")
                        .HasColumnType("bit");

                    b.Property<decimal>("ValorFixado")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("DotacaoId")
                        .IsUnique()
                        .HasFilter("[DotacaoId] IS NOT NULL");

                    b.HasIndex("LoaId");

                    b.ToTable("LoaItensDespesaFixada", "financas");
                });

            modelBuilder.Entity("Tensorroot.Gov.Modules.Financas.Domain.Planejamento.Loa.LeiOrcamentariaAnual", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AnoLei")
                        .HasColumnType("int");

                    b.Property<int>("Exercicio")
                        .HasColumnType("int");

                    b.Property<Guid>("LdoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("LimiteSuplementacaoPercentual")
                        .HasColumnType("decimal(9,4)");

                    b.Property<string>("NumeroLei")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<Guid>("PpaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Situacao")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "Exercicio");

                    b.ToTable("LeisOrcamentarias", "financas");
                });

            modelBuilder.Entity("Tensorroot.Gov.Modules.Financas.Domain.Planejamento.Loa.ReceitaPrevista", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("FonteDeRecurso")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<Guid>("LoaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("ValorPrevisto")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("LoaId");

                    b.ToTable("LoaReceitasPrevistas", "financas");
                });

            modelBuilder.Entity("Tensorroot.Gov.Modules.Financas.Domain.Planejamento.Ppa.AcaoPpa", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("FuncionalProgramatica")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Produto")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid>("ProgramaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("UnidadeMedida")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.HasIndex("ProgramaId");

                    b.ToTable("PpaAcoes", "financas");
                });

            modelBuilder.Entity("Tensorroot.Gov.Modules.Financas.Domain.Planejamento.Ppa.MetaAcao", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AcaoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Ano")
                        .HasColumnType("int");

                    b.Property<decimal>("MetaFinanceira")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("MetaFisica")
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("Regiao")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("UnidadeMedida")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.HasIndex("AcaoId");

                    b.ToTable("PpaMetas", "financas");
                });

            modelBuilder.Entity("Tensorroot.Gov.Modules.Financas.Domain.Planejamento.Ppa.PlanoPlurianual", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AnoFim")
                        .HasColumnType("int");

                    b.Property<int>("AnoInicio")
                        .HasColumnType("int");

                    b.Property<int>("AnoLei")
                        .HasColumnType("int");

                    b.Property<string>("NumeroLei")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("Situacao")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "AnoInicio");

                    b.ToTable("PlanosPlurianuais", "financas");
                });

            modelBuilder.Entity("Tensorroot.Gov.Modules.Financas.Domain.Planejamento.Ppa.Programa", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Indicador")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal>("IndicadorLinhaBase")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("IndicadorMeta")
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Objetivo")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<Guid>("PpaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("PublicoAlvo")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("PpaId");

                    b.ToTable("PpaProgramas", "financas");
                });

            modelBuilder.Entity("Tensorroot.Gov.Modules.Financas.Domain.Receitas.ReceitaArrecadada", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateOnly>("Data")
                        .HasColumnType("date");

                    b.Property<Guid>("OrigemId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Valor")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "OrigemId");

                    b.ToTable("ReceitasArrecadadas", "financas");
                });

            modelBuilder.Entity("Tensorroot.Gov.Modules.Financas.Domain.RestosAPagar.RestoAPagar", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Classificacao")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<Guid>("EmpenhoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ExercicioInscricao")
                        .HasColumnType("int");

                    b.Property<int>("ExercicioOrigem")
                        .HasColumnType("int");

                    b.Property<string>("Situacao")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("ValorCancelado")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ValorInscrito")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ValorLiquidado")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ValorPago")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("EmpenhoId");

                    b.HasIndex("TenantId", "ExercicioInscricao");

                    b.ToTable("RestosAPagar", "financas");
                });

            modelBuilder.Entity("Tensorroot.Gov.Modules.Financas.Domain.Tesouraria.ContaFinanceira", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<decimal>("Saldo")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("SaldoInicial")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Situacao")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "Nome")
                        .IsUnique();

                    b.ToTable("ContasFinanceiras", "financas");
                });

            modelBuilder.Entity("Tensorroot.Gov.SharedKernel.InboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("EventType")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Handler")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("ProcessedOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("EventId", "Handler", "TenantId")
                        .IsUnique();

                    b.ToTable("InboxMessages", "financas");
                });

            modelBuilder.Entity("Tensorroot.Gov.SharedKernel.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("int");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DeadLetteredOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Error")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("NextAttemptUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("OccurredOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ProcessedOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("ProcessedOnUtc", "DeadLetteredOnUtc", "NextAttemptUtc");

                    b.ToTable("OutboxMessages", "financas");
                });

            modelBuilder.Entity("Tensorroot.Gov.Modules.Financas.Domain.Contabilidade.EventosContabeis.EventoContabil", b =>
                {
                    b.OwnsMany("Tensorroot.Gov.Modules.Financas.Domain.Contabilidade.EventosContabeis.LinhaRoteiro", "Linhas", b1 =>
                        {
                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int");

                            SqlServerPropertyBuilderExtensions.UseIdentityColumn(b1.Property<int>("Id"));

                            b1.Property<string>("BaseValor")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("nvarchar(20)");

                            b1.Property<string>("CodigoContaFixo")
                                .HasMaxLength(30)
                                .HasColumnType("nvarchar(30)");

                            b1.Property<Guid>("EventoContabilId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Lado")
                                .IsRequired()
                                .HasMaxLength(10)
                                .HasColumnType("nvarchar(10)");

                            b1.Property<string>("NaturezaInformacao")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("nvarchar(20)");

                            b1.Property<string>("Papel")
                                .HasMaxLength(40)
                                .HasColumnType("nvarchar(40)");

                            b1.HasKey("Id");

                            b1.HasIndex("EventoContabilId");

                            b1.ToTable("LinhasRoteiroContabil", "financas");

                            b1.WithOwner()
                                .HasForeignKey("EventoContabilId");
                        });

                    b.Navigation("Linhas");
                });

            modelBuilder.Entity("Tensorroot.Gov.Modules.Financas.Domain.Contabilidade.Lancamentos.LancamentoContabil", b =>
                {
                    b.OwnsMany("Tensorroot.Gov.Modules.Financas.Domain.Contabilidade.Lancamentos.PartidaContabil", "Partidas", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("CodigoConta")
                                .IsRequired()
                                .HasMaxLength(30)
                                .HasColumnType("nvarchar(30)");

                            b1.Property<Guid>("ContaId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Lado")
                                .IsRequired()
                                .HasMaxLength(10)
                                .HasColumnType("nvarchar(10)");

                            b1.Property<Guid>("LancamentoContabilId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("NaturezaInformacao")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("nvarchar(20)");

                            b1.Property<decimal>("Valor")
                                .HasColumnType("decimal(18,2)");

                            b1.HasKey("Id");

                            b1.HasIndex("ContaId");

                            b1.HasIndex("LancamentoContabilId");

                            b1.ToTable("PartidasContabeis", "financas");

                            b1.WithOwner()
                                .HasForeignKey("LancamentoContabilId");
                        });

                    b.Navigation("Partidas");
                });

            modelBuilder.Entity("Tensorroot.Gov.Modules.Financas.Domain.Credores.CredorCadastrado", b =>
                {
                    b.OwnsOne("Tensorroot.Gov.Modules.Financas.Domain.ValueObjects.ContaBancaria", "DadosBancarios", b1 =>
                        {
                            b1.Property<Guid>("CredorCadastradoId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Agencia")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("nvarchar(20)")
                                .HasColumnName("Agencia");

                            b1.Property<string>("Banco")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("nvarchar(20)")
                                .HasColumnName("Banco");

                            b1.Property<string>("Conta")
                                .IsRequired()
                                .HasMaxLength(30)
                                .HasColumnType("nvarchar(30)")
                                .HasColumnName("ContaNumero");

                            b1.Property<string>("Pix")
                                .HasMaxLength(140)
                                .HasColumnType("nvarchar(140)")
                                .HasColumnName("Pix");

                            b1.HasKey("CredorCadastradoId");

                            b1.ToTable("Credores", "financas");

                            b1.WithOwner()
                                .HasForeignKey("CredorCadastradoId");
                        });

                    b.Navigation("DadosBancarios");
                });

            modelBuilder.Entity("Tensorroot.Gov.Modules.Financas.Domain.Dotacoes.DotacaoOrcamentaria", b =>
                {
                    b.OwnsOne("Tensorroot.Gov.Modules.Financas.Domain.ValueObjects.ClassificacaoOrcamentaria", "Classificacao", b1 =>
                        {
                            b1.Property<Guid>("DotacaoOrcamentariaId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("CategoriaEconomica")
                                .IsRequired()
                                .HasMaxLength(30)
                                .HasColumnType("nvarchar(30)")
                                .HasColumnName("CategoriaEconomica");

                            b1.Property<string>("FonteDeRecurso")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("nvarchar(20)")
                                .HasColumnName("FonteDeRecurso");

                            b1.Property<string>("FuncionalProgramatica")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("nvarchar(50)")
                                .HasColumnName("FuncionalProgramatica");

                            b1.Property<string>("Orgao")
                                .IsRequired()
                                .HasMaxLength(10)
                                .HasColumnType("nvarchar(10)")
                                .HasColumnName("Orgao");

                            b1.Property<string>("UnidadeOrcamentaria")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("nvarchar(20)")
                                .HasColumnName("UnidadeOrcamentaria");

                            b1.HasKey("DotacaoOrcamentariaId");

                            b1.ToTable("Dotacoes", "financas");

                            b1.WithOwner()
                                .HasForeignKey("DotacaoOrcamentariaId");
                        });

                    b.Navigation("Classificacao")
                        .IsRequired();
                });

            modelBuilder.Entity("Tensorroot.Gov.Modules.Financas.Domain.Empenhos.Empenho", b =>
                {
                    b.OwnsOne("Tensorroot.Gov.Modules.Financas.Domain.ValueObjects.Credor", "Credor", b1 =>
                        {
                            b1.Property<Guid>("EmpenhoId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Documento")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("nvarchar(20)")
                                .HasColumnName("CredorDocumento");

                            b1.Property<string>("Nome")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("nvarchar(200)")
                                .HasColumnName("CredorNome");

                            b1.Property<string>("Tipo")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("nvarchar(20)")
                                .HasColumnName("CredorTipo");

                            b1.HasKey("EmpenhoId");

                            b1.ToTable("Empenhos", "financas");

                            b1.WithOwner()
                                .HasForeignKey("EmpenhoId");
                        });

                    b.Navigation("Credor")
                        .IsRequired();
                });

            modelBuilder.Entity("Tensorroot.Gov.Modules.Financas.Domain.Liquidacoes.Liquidacao", b =>
                {
                    b.OwnsOne("Tensorroot.Gov.Modules.Financas.Domain.ValueObjects.DocumentoComprobatorio", "Documento", b1 =>
                        {
                            b1.Property<Guid>("LiquidacaoId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("ChaveAcessoNfse")
                                .HasMaxLength(44)
                                .HasColumnType("nvarchar(44)")
                                .HasColumnName("DocumentoChaveNfse");

                            b1.Property<DateOnly?>("DataEmissao")
                                .HasColumnType("date")
                                .HasColumnName("DocumentoDataEmissao");

                            b1.Property<string>("Numero")
                                .HasMaxLength(60)
                                .HasColumnType("nvarchar(60)")
                                .HasColumnName("DocumentoNumero");

                            b1.Property<string>("Tipo")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("nvarchar(20)")
                                .HasColumnName("DocumentoTipo");

                            b1.HasKey("LiquidacaoId");

                            b1.ToTable("Liquidacoes", "financas");

                            b1.WithOwner()
                                .HasForeignKey("LiquidacaoId");
                        });

                    b.Navigation("Documento")
                        .IsRequired();
                });

            modelBuilder.Entity("Tensorroot.Gov.Modules.Financas.Domain.Pagamentos.OrdemDePagamento", b =>
                {
                    b.OwnsMany("Tensorroot.Gov.Modules.Financas.Domain.Pagamentos.ItemPagamento", "Itens", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<Guid>("LiquidacaoId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<Guid>("OrdemDePagamentoId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<decimal>("Valor")
                                .HasColumnType("decimal(18,2)");

                            b1.HasKey("Id");

                            b1.HasIndex("LiquidacaoId");

                            b1.HasIndex("OrdemDePagamentoId");

                            b1.ToTable("ItensPagamento", "financas");

                            b1.WithOwner()
                                .HasForeignKey("OrdemDePagamentoId");
                        });

                    b.OwnsOne("Tensorroot.Gov.Modules.Financas.Domain.ValueObjects.ContaBancaria", "ContaBancaria", b1 =>
                        {
                            b1.Property<Guid>("OrdemDePagamentoId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Agencia")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("nvarchar(20)")
                                .HasColumnName("ContaAgencia");

                            b1.Property<string>("Banco")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("nvarchar(20)")
                                .HasColumnName("ContaBanco");

                            b1.Property<string>("Conta")
                                .IsRequired()
                                .HasMaxLength(30)
                                .HasColumnType("nvarchar(30)")
                                .HasColumnName("ContaNumero");

                            b1.Property<string>("Pix")
                                .HasMaxLength(140)
                                .HasColumnType("nvarchar(140)")
                                .HasColumnName("ContaPix");

                            b1.HasKey("OrdemDePagamentoId");

                            b1.ToTable("OrdensDePagamento", "financas");

                            b1.WithOwner()
                                .HasForeignKey("OrdemDePagamentoId");
                        });

                    b.Navigation("ContaBancaria")
                        .IsRequired();

                    b.Navigation("Itens");
                });

            modelBuilder.Entity("Tensorroot.Gov.Modules.Financas.Domain.Planejamento.Ldo.AnexoLdo", b =>
                {
                    b.HasOne("Tensorroot.Gov.Modules.Financas.Domain.Planejamento.Ldo.LeiDiretrizes", null)
                        .WithMany("Anexos")
                        .HasForeignKey("LdoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Tensorroot.Gov.Modules.Financas.Domain.Planejamento.Ldo.MetaFiscal", b =>
                {
                    b.HasOne("Tensorroot.Gov.Modules.Financas.Domain.Planejamento.Ldo.LeiDiretrizes", null)
                        .WithMany("MetasFiscais")
                        .HasForeignKey("LdoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Tensorroot.Gov.Modules.Financas.Domain.Planejamento.Ldo.PrioridadeLdo", b =>
                {
                    b.HasOne("Tensorroot.Gov.Modules.Financas.Domain.Planejamento.Ldo.LeiDiretrizes", null)
                        .WithMany("Prioridades")
                        .HasForeignKey("LdoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Tensorroot.Gov.Modules.Financas.Domain.Planejamento.Loa.ItemDespesaFixada", b =>
                {
                    b.HasOne("Tensorroot.Gov.Modules.Financas.Domain.Planejamento.Loa.LeiOrcamentariaAnual", null)
                        .WithMany("Itens")
                        .HasForeignKey("LoaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Tensorroot.Gov.Modules.Financas.Domain.ValueObjects.ClassificacaoOrcamentaria", "Classificacao", b1 =>
                        {
                            b1.Property<Guid>("ItemDespesaFixadaId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("CategoriaEconomica")
                                .IsRequired()
                                .HasMaxLength(30)
                                .HasColumnType("nvarchar(30)")
                                .HasColumnName("CategoriaEconomica");

                            b1.Property<string>("FonteDeRecurso")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("nvarchar(20)")
                                .HasColumnName("FonteDeRecurso");

                            b1.Property<string>("FuncionalProgramatica")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("nvarchar(50)")
                                .HasColumnName("FuncionalProgramatica");

                            b1.Property<string>("Orgao")
                                .IsRequired()
                                .HasMaxLength(10)
                                .HasColumnType("nvarchar(10)")
                                .HasColumnName("Orgao");

                            b1.Property<string>("UnidadeOrcamentaria")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("nvarchar(20)")
                                .HasColumnName("UnidadeOrcamentaria");

                            b1.HasKey("ItemDespesaFixadaId");

                            b1.ToTable("LoaItensDespesaFixada", "financas");

                            b1.WithOwner()
                                .HasForeignKey("ItemDespesaFixadaId");
                        });

                    b.Navigation("Classificacao")
                        .IsRequired();
                });

            modelBuilder.Entity("Tensorroot.Gov.Modules.Financas.Domain.Planejamento.Loa.ReceitaPrevista", b =>
                {
                    b.HasOne("Tensorroot.Gov.Modules.Financas.Domain.Planejamento.Loa.LeiOrcamentariaAnual", null)
                        .WithMany("Receitas")
                        .HasForeignKey("LoaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Tensorroot.Gov.Modules.Financas.Domain.Planejamento.Loa.NaturezaReceita", "Natureza", b1 =>
                        {
                            b1.Property<Guid>("ReceitaPrevistaId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Categoria")
                                .IsRequired()
                                .HasMaxLength(30)
                                .HasColumnType("nvarchar(30)")
                                .HasColumnName("ReceitaCategoria");

                            b1.Property<string>("Especie")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("nvarchar(20)")
                                .HasColumnName("ReceitaEspecie");

                            b1.Property<string>("Origem")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("nvarchar(20)")
                                .HasColumnName("ReceitaOrigem");

                            b1.Property<string>("Rubrica")
                                .IsRequired()
                                .HasMaxLength(40)
                                .HasColumnType("nvarchar(40)")
                                .HasColumnName("ReceitaRubrica");

                            b1.HasKey("ReceitaPrevistaId");

                            b1.ToTable("LoaReceitasPrevistas", "financas");

                            b1.WithOwner()
                                .HasForeignKey("ReceitaPrevistaId");
                        });

                    b.Navigation("Natureza")
                        .IsRequired();
                });

            modelBuilder.Entity("Tensorroot.Gov.Modules.Financas.Domain.Planejamento.Ppa.AcaoPpa", b =>
                {
                    b.HasOne("Tensorroot.Gov.Modules.Financas.Domain.Planejamento.Ppa.Programa", null)
                        .WithMany("Acoes")
                        .HasForeignKey("ProgramaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Tensorroot.Gov.Modules.Financas.Domain.Planejamento.Ppa.MetaAcao", b =>
                {
                    b.HasOne("Tensorroot.Gov.Modules.Financas.Domain.Planejamento.Ppa.AcaoPpa", null)
                        .WithMany("Metas")
                        .HasForeignKey("AcaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Tensorroot.Gov.Modules.Financas.Domain.Planejamento.Ppa.Programa", b =>
                {
                    b.HasOne("Tensorroot.Gov.Modules.Financas.Domain.Planejamento.Ppa.PlanoPlurianual", null)
                        .WithMany("Programas")
                        .HasForeignKey("PpaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Tensorroot.Gov.Modules.Financas.Domain.Tesouraria.ContaFinanceira", b =>
                {
                    b.OwnsOne("Tensorroot.Gov.Modules.Financas.Domain.ValueObjects.ContaBancaria", "DadosBancarios", b1 =>
                        {
                            b1.Property<Guid>("ContaFinanceiraId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Agencia")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("nvarchar(20)")
                                .HasColumnName("Agencia");

                            b1.Property<string>("Banco")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("nvarchar(20)")
                                .HasColumnName("Banco");

                            b1.Property<string>("Conta")
                                .IsRequired()
                                .HasMaxLength(30)
                                .HasColumnType("nvarchar(30)")
                                .HasColumnName("ContaNumero");

                            b1.Property<string>("Pix")
                                .HasMaxLength(140)
                                .HasColumnType("nvarchar(140)")
                                .HasColumnName("Pix");

                            b1.HasKey("ContaFinanceiraId");

                            b1.ToTable("ContasFinanceiras", "financas");

                            b1.WithOwner()
                                .HasForeignKey("ContaFinanceiraId");
                        });

                    b.OwnsMany("Tensorroot.Gov.Modules.Financas.Domain.Tesouraria.MovimentoFinanceiro", "Movimentos", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<bool>("Conciliado")
                                .HasColumnType("bit");

                            b1.Property<Guid>("ContaFinanceiraId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<Guid>("ContaId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<Guid?>("ContraparteContaId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<DateOnly>("Data")
                                .HasColumnType("date");

                            b1.Property<DateOnly?>("DataConciliacao")
                                .HasColumnType("date");

                            b1.Property<string>("Documento")
                                .HasMaxLength(60)
                                .HasColumnType("nvarchar(60)");

                            b1.Property<string>("Historico")
                                .IsRequired()
                                .HasMaxLength(300)
                                .HasColumnType("nvarchar(300)");

                            b1.Property<Guid?>("OrigemReferenciaId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<decimal>("SaldoApos")
                                .HasColumnType("decimal(18,2)");

                            b1.Property<string>("Tipo")
                                .IsRequired()
                                .HasMaxLength(25)
                                .HasColumnType("nvarchar(25)");

                            b1.Property<decimal>("Valor")
                                .HasColumnType("decimal(18,2)");

                            b1.HasKey("Id");

                            b1.HasIndex("ContaFinanceiraId");

                            b1.HasIndex("Data");

                            b1.ToTable("MovimentosFinanceiros", "financas");

                            b1.WithOwner()
                                .HasForeignKey("ContaFinanceiraId");
                        });

                    b.Navigation("DadosBancarios");

                    b.Navigation("Movimentos");
                });

            modelBuilder.Entity("Tensorroot.Gov.Modules.Financas.Domain.Planejamento.Ldo.LeiDiretrizes", b =>
                {
                    b.Navigation("Anexos");

                    b.Navigation("MetasFiscais");

                    b.Navigation("Prioridades");
                });

            modelBuilder.Entity("Tensorroot.Gov.Modules.Financas.Domain.Planejamento.Loa.LeiOrcamentariaAnual", b =>
                {
                    b.Navigation("Itens");

                    b.Navigation("Receitas");
                });

            modelBuilder.Entity("Tensorroot.Gov.Modules.Financas.Domain.Planejamento.Ppa.AcaoPpa", b =>
                {
                    b.Navigation("Metas");
                });

            modelBuilder.Entity("Tensorroot.Gov.Modules.Financas.Domain.Planejamento.Ppa.PlanoPlurianual", b =>
                {
                    b.Navigation("Programas");
                });

            modelBuilder.Entity("Tensorroot.Gov.Modules.Financas.Domain.Planejamento.Ppa.Programa", b =>
                {
                    b.Navigation("Acoes");
                });
#pragma warning restore 612, 618
        }
    }
}
