// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Tensorroot.Gov.Modules.Legislativo.Infrastructure.Persistence;

#nullable disable

namespace Tensorroot.Gov.Modules.Legislativo.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(LegislativoDbContext))]
    [Migration("20260622195258_AddNormasDiarioTribunaComissao")]
    partial class AddNormasDiarioTribunaComissao
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("legislativo")
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Tensorroot.Gov.BuildingBlocks.Infrastructure.Auditing.AuditTrail", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("AffectedColumns")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EntityId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EntityName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("IpAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NewValues")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OldValues")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("TimestampUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "TimestampUtc");

                    b.ToTable("AuditTrail", "legislativo");
                });

            modelBuilder.Entity("Tensorroot.Gov.Modules.Legislativo.Domain.Comissoes.Comissao", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Situacao")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "Situacao");

                    b.ToTable("Comissoes", "legislativo");
                });

            modelBuilder.Entity("Tensorroot.Gov.Modules.Legislativo.Domain.DiarioOficial.EdicaoDiario", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Ano")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("DataPublicacao")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid?>("EdicaoOriginalId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("HashConteudo")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<int>("Numero")
                        .HasColumnType("int");

                    b.Property<string>("Situacao")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "Situacao");

                    b.HasIndex("TenantId", "Ano", "Numero")
                        .IsUnique();

                    b.ToTable("DiarioEdicoes", "legislativo");
                });

            modelBuilder.Entity("Tensorroot.Gov.Modules.Legislativo.Domain.Normas.Norma", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Ano")
                        .HasColumnType("int");

                    b.Property<DateOnly>("DataPromulgacao")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("DataRevogacao")
                        .HasColumnType("date");

                    b.Property<string>("Ementa")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<Guid?>("NormaRevogadoraId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Numero")
                        .HasColumnType("int");

                    b.Property<Guid?>("ProposicaoOrigemId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("SituacaoVigencia")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TextoArticulado")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "SituacaoVigencia");

                    b.HasIndex("TenantId", "Tipo", "Numero", "Ano")
                        .IsUnique();

                    b.ToTable("Normas", "legislativo");
                });

            modelBuilder.Entity("Tensorroot.Gov.Modules.Legislativo.Domain.Proposicoes.Proposicao", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Autoria")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)");

                    b.Property<DateOnly>("DataApresentacao")
                        .HasColumnType("date");

                    b.Property<string>("Ementa")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("NumeroAutografo")
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("Protocolo")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("Regime")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Situacao")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "Protocolo")
                        .IsUnique();

                    b.HasIndex("TenantId", "Situacao");

                    b.ToTable("Proposicoes", "legislativo");
                });

            modelBuilder.Entity("Tensorroot.Gov.Modules.Legislativo.Domain.Sessoes.Sessao", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("DataHora")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Situacao")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("TotalMembros")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "Situacao");

                    b.ToTable("Sessoes", "legislativo");
                });

            modelBuilder.Entity("Tensorroot.Gov.Modules.Legislativo.Domain.Tribuna.TribunaSessao", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("SessaoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<TimeSpan>("TempoPadraoOrador")
                        .HasColumnType("time");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "SessaoId")
                        .IsUnique();

                    b.ToTable("Tribunas", "legislativo");
                });

            modelBuilder.Entity("Tensorroot.Gov.Modules.Legislativo.Domain.Vereadores.Vereador", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CargoMesa")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("LegislaturaFim")
                        .HasColumnType("int");

                    b.Property<int>("LegislaturaInicio")
                        .HasColumnType("int");

                    b.Property<string>("NomeCivil")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("NomeParlamentar")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Partido")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Situacao")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "NomeParlamentar");

                    b.ToTable("Vereadores", "legislativo");
                });

            modelBuilder.Entity("Tensorroot.Gov.Modules.Legislativo.Domain.Votacoes.Votacao", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("MaioriaExigida")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("Presentes")
                        .HasColumnType("int");

                    b.Property<Guid>("ProposicaoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Resultado")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<Guid>("SessaoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Situacao")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("TotalMembros")
                        .HasColumnType("int");

                    b.Property<int>("Turno")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "ProposicaoId");

                    b.ToTable("Votacoes", "legislativo");
                });

            modelBuilder.Entity("Tensorroot.Gov.SharedKernel.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("int");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DeadLetteredOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Error")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("NextAttemptUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("OccurredOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ProcessedOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("ProcessedOnUtc", "DeadLetteredOnUtc", "NextAttemptUtc");

                    b.ToTable("OutboxMessages", "legislativo");
                });

            modelBuilder.Entity("Tensorroot.Gov.Modules.Legislativo.Domain.Comissoes.Comissao", b =>
                {
                    b.OwnsMany("Tensorroot.Gov.Modules.Legislativo.Domain.Comissoes.MembroComissao", "Membros", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Cargo")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("nvarchar(20)");

                            b1.Property<Guid>("ComissaoOwnerId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Papel")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("nvarchar(20)");

                            b1.Property<Guid>("VereadorId")
                                .HasColumnType("uniqueidentifier");

                            b1.HasKey("Id");

                            b1.HasIndex("ComissaoOwnerId");

                            b1.ToTable("ComissoesMembros", "legislativo");

                            b1.WithOwner()
                                .HasForeignKey("ComissaoOwnerId");
                        });

                    b.Navigation("Membros");
                });

            modelBuilder.Entity("Tensorroot.Gov.Modules.Legislativo.Domain.DiarioOficial.EdicaoDiario", b =>
                {
                    b.OwnsMany("Tensorroot.Gov.Modules.Legislativo.Domain.DiarioOficial.MateriaDiario", "Materias", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Conteudo")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<Guid>("EdicaoOwnerId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<int>("Ordem")
                                .HasColumnType("int");

                            b1.Property<Guid?>("ReferenciaId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Tipo")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("nvarchar(20)");

                            b1.Property<string>("Titulo")
                                .IsRequired()
                                .HasMaxLength(300)
                                .HasColumnType("nvarchar(300)");

                            b1.HasKey("Id");

                            b1.HasIndex("EdicaoOwnerId");

                            b1.ToTable("DiarioMaterias", "legislativo");

                            b1.WithOwner()
                                .HasForeignKey("EdicaoOwnerId");
                        });

                    b.Navigation("Materias");
                });

            modelBuilder.Entity("Tensorroot.Gov.Modules.Legislativo.Domain.Normas.Norma", b =>
                {
                    b.OwnsMany("Tensorroot.Gov.Modules.Legislativo.Domain.Normas.EventoVigencia", "HistoricoVigencia", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<DateOnly>("Data")
                                .HasColumnType("date");

                            b1.Property<Guid>("NormaOwnerId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<Guid?>("NormaReferenciaId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Observacao")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Tipo")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("nvarchar(20)");

                            b1.HasKey("Id");

                            b1.HasIndex("NormaOwnerId");

                            b1.ToTable("NormasHistoricoVigencia", "legislativo");

                            b1.WithOwner()
                                .HasForeignKey("NormaOwnerId");
                        });

                    b.Navigation("HistoricoVigencia");
                });

            modelBuilder.Entity("Tensorroot.Gov.Modules.Legislativo.Domain.Proposicoes.Proposicao", b =>
                {
                    b.OwnsMany("Tensorroot.Gov.Modules.Legislativo.Domain.Proposicoes.Emenda", "Emendas", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Autoria")
                                .IsRequired()
                                .HasMaxLength(400)
                                .HasColumnType("nvarchar(400)");

                            b1.Property<DateOnly>("Data")
                                .HasColumnType("date");

                            b1.Property<Guid>("ProposicaoId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<Guid>("ProposicaoOwnerId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Texto")
                                .IsRequired()
                                .HasMaxLength(4000)
                                .HasColumnType("nvarchar(4000)");

                            b1.HasKey("Id");

                            b1.HasIndex("ProposicaoOwnerId");

                            b1.ToTable("ProposicoesEmendas", "legislativo");

                            b1.WithOwner()
                                .HasForeignKey("ProposicaoOwnerId");
                        });

                    b.OwnsMany("Tensorroot.Gov.Modules.Legislativo.Domain.Proposicoes.Substitutivo", "Substitutivos", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Autoria")
                                .IsRequired()
                                .HasMaxLength(400)
                                .HasColumnType("nvarchar(400)");

                            b1.Property<DateOnly>("Data")
                                .HasColumnType("date");

                            b1.Property<Guid>("ProposicaoId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<Guid>("ProposicaoOwnerId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Texto")
                                .IsRequired()
                                .HasMaxLength(8000)
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("Id");

                            b1.HasIndex("ProposicaoOwnerId");

                            b1.ToTable("ProposicoesSubstitutivos", "legislativo");

                            b1.WithOwner()
                                .HasForeignKey("ProposicaoOwnerId");
                        });

                    b.OwnsMany("Tensorroot.Gov.Modules.Legislativo.Domain.Proposicoes.Tramitacao", "Tramitacoes", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Comissao")
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)");

                            b1.Property<DateOnly>("Data")
                                .HasColumnType("date");

                            b1.Property<string>("Fase")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("nvarchar(20)");

                            b1.Property<bool?>("ParecerFavoravel")
                                .HasColumnType("bit");

                            b1.Property<Guid>("ProposicaoId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<Guid>("ProposicaoOwnerId")
                                .HasColumnType("uniqueidentifier");

                            b1.HasKey("Id");

                            b1.HasIndex("ProposicaoOwnerId");

                            b1.ToTable("ProposicoesTramitacoes", "legislativo");

                            b1.WithOwner()
                                .HasForeignKey("ProposicaoOwnerId");
                        });

                    b.Navigation("Emendas");

                    b.Navigation("Substitutivos");

                    b.Navigation("Tramitacoes");
                });

            modelBuilder.Entity("Tensorroot.Gov.Modules.Legislativo.Domain.Sessoes.Sessao", b =>
                {
                    b.OwnsMany("Tensorroot.Gov.Modules.Legislativo.Domain.Sessoes.ItemOrdemDoDia", "OrdemDoDia", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<int>("Ordem")
                                .HasColumnType("int");

                            b1.Property<Guid>("ProposicaoId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<Guid>("SessaoOwnerId")
                                .HasColumnType("uniqueidentifier");

                            b1.HasKey("Id");

                            b1.HasIndex("SessaoOwnerId");

                            b1.ToTable("SessoesOrdemDoDia", "legislativo");

                            b1.WithOwner()
                                .HasForeignKey("SessaoOwnerId");
                        });

                    b.OwnsMany("Tensorroot.Gov.Modules.Legislativo.Domain.Sessoes.Presenca", "Presencas", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<DateTimeOffset>("RegistradaEm")
                                .HasColumnType("datetimeoffset");

                            b1.Property<Guid>("SessaoOwnerId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<Guid>("VereadorId")
                                .HasColumnType("uniqueidentifier");

                            b1.HasKey("Id");

                            b1.HasIndex("SessaoOwnerId");

                            b1.ToTable("SessoesPresencas", "legislativo");

                            b1.WithOwner()
                                .HasForeignKey("SessaoOwnerId");
                        });

                    b.Navigation("OrdemDoDia");

                    b.Navigation("Presencas");
                });

            modelBuilder.Entity("Tensorroot.Gov.Modules.Legislativo.Domain.Tribuna.TribunaSessao", b =>
                {
                    b.OwnsMany("Tensorroot.Gov.Modules.Legislativo.Domain.Tribuna.InscricaoOrador", "Inscricoes", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<int>("Apartes")
                                .HasColumnType("int");

                            b1.Property<DateTimeOffset?>("EncerradoEm")
                                .HasColumnType("datetimeoffset");

                            b1.Property<string>("Fase")
                                .IsRequired()
                                .HasMaxLength(30)
                                .HasColumnType("nvarchar(30)");

                            b1.Property<DateTimeOffset?>("IniciadoEm")
                                .HasColumnType("datetimeoffset");

                            b1.Property<int>("Ordem")
                                .HasColumnType("int");

                            b1.Property<DateTimeOffset?>("PausaIniciadaEm")
                                .HasColumnType("datetimeoffset");

                            b1.Property<string>("Situacao")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("nvarchar(20)");

                            b1.Property<TimeSpan>("TempoConcedido")
                                .HasColumnType("time");

                            b1.Property<Guid>("TribunaOwnerId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<Guid>("VereadorId")
                                .HasColumnType("uniqueidentifier");

                            b1.HasKey("Id");

                            b1.HasIndex("TribunaOwnerId");

                            b1.ToTable("TribunaInscricoes", "legislativo");

                            b1.WithOwner()
                                .HasForeignKey("TribunaOwnerId");

                            b1.OwnsMany("Tensorroot.Gov.Modules.Legislativo.Domain.Tribuna.PausaFala", "Pausas", b2 =>
                                {
                                    b2.Property<int>("Id")
                                        .ValueGeneratedOnAdd()
                                        .HasColumnType("int");

                                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b2.Property<int>("Id"));

                                    b2.Property<DateTimeOffset>("Fim")
                                        .HasColumnType("datetimeoffset");

                                    b2.Property<DateTimeOffset>("Inicio")
                                        .HasColumnType("datetimeoffset");

                                    b2.Property<Guid>("InscricaoOwnerId")
                                        .HasColumnType("uniqueidentifier");

                                    b2.HasKey("Id");

                                    b2.HasIndex("InscricaoOwnerId");

                                    b2.ToTable("TribunaPausas", "legislativo");

                                    b2.WithOwner()
                                        .HasForeignKey("InscricaoOwnerId");
                                });

                            b1.Navigation("Pausas");
                        });

                    b.Navigation("Inscricoes");
                });

            modelBuilder.Entity("Tensorroot.Gov.Modules.Legislativo.Domain.Votacoes.Votacao", b =>
                {
                    b.OwnsMany("Tensorroot.Gov.Modules.Legislativo.Domain.Votacoes.Voto", "Votos", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<DateTimeOffset>("RegistradoEm")
                                .HasColumnType("datetimeoffset");

                            b1.Property<string>("Sentido")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("nvarchar(20)");

                            b1.Property<Guid>("VereadorId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<Guid>("VotacaoOwnerId")
                                .HasColumnType("uniqueidentifier");

                            b1.HasKey("Id");

                            b1.HasIndex("VotacaoOwnerId");

                            b1.ToTable("VotacoesVotos", "legislativo");

                            b1.WithOwner()
                                .HasForeignKey("VotacaoOwnerId");
                        });

                    b.Navigation("Votos");
                });
#pragma warning restore 612, 618
        }
    }
}
