// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Tensorroot.Gov.Modules.RecursosHumanos.Infrastructure.Persistence;

#nullable disable

namespace Tensorroot.Gov.Modules.RecursosHumanos.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(RecursosHumanosDbContext))]
    [Migration("20260621180039_Inicial")]
    partial class Inicial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("recursoshumanos")
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Tensorroot.Gov.BuildingBlocks.Infrastructure.Auditing.AuditTrail", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("AffectedColumns")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EntityId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EntityName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("IpAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NewValues")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OldValues")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("TimestampUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "TimestampUtc");

                    b.ToTable("AuditTrail", "recursoshumanos");
                });

            modelBuilder.Entity("Tensorroot.Gov.Modules.RecursosHumanos.Domain.Cargos.Cargo", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Denominacao")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("LeiCriacao")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid?>("PlanoDeCargosId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("QuantidadeVagas")
                        .HasColumnType("int");

                    b.Property<string>("Regime")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Situacao")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("VagasOcupadas")
                        .HasColumnType("int");

                    b.Property<decimal>("Vencimento")
                        .HasColumnType("decimal(18,2)");

                    b.ComplexProperty<Dictionary<string, object>>("Lotacao", "Tensorroot.Gov.Modules.RecursosHumanos.Domain.Cargos.Cargo.Lotacao#Lotacao", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("CodigoLotacaoTributaria")
                                .HasMaxLength(30)
                                .HasColumnType("nvarchar(30)")
                                .HasColumnName("LotacaoCodigoTributaria");

                            b1.Property<string>("DenominacaoUnidade")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("nvarchar(200)")
                                .HasColumnName("LotacaoDenominacaoUnidade");

                            b1.Property<string>("InscricaoEstabelecimento")
                                .IsRequired()
                                .HasMaxLength(30)
                                .HasColumnType("nvarchar(30)")
                                .HasColumnName("LotacaoInscricaoEstabelecimento");
                        });

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "Situacao", "Tipo");

                    b.ToTable("Cargos", "recursoshumanos");
                });

            modelBuilder.Entity("Tensorroot.Gov.Modules.RecursosHumanos.Domain.Folha.FolhaDePagamento", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Competencia")
                        .HasColumnType("int");

                    b.Property<DateOnly?>("DataCalculo")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("DataFechamento")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("DataPagamento")
                        .HasColumnType("date");

                    b.Property<string>("Situacao")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("TotalDescontos")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalLiquido")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalProventos")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "Competencia")
                        .IsUnique();

                    b.ToTable("FolhasDePagamento", "recursoshumanos");
                });

            modelBuilder.Entity("Tensorroot.Gov.Modules.RecursosHumanos.Domain.Servidores.Servidor", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CargoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Cpf")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)");

                    b.Property<DateOnly?>("DataDesligamento")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("DataEstabilidade")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("DataExercicio")
                        .HasColumnType("date");

                    b.Property<DateOnly>("DataNomeacao")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("DataPosse")
                        .HasColumnType("date");

                    b.Property<string>("Matricula")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Regime")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Situacao")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.ComplexProperty<Dictionary<string, object>>("DadosPessoais", "Tensorroot.Gov.Modules.RecursosHumanos.Domain.Servidores.Servidor.DadosPessoais#DadosPessoais", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<DateOnly>("DataNascimento")
                                .HasColumnType("date")
                                .HasColumnName("DataNascimento");

                            b1.Property<string>("Nome")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("nvarchar(200)")
                                .HasColumnName("Nome");
                        });

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "Matricula")
                        .IsUnique();

                    b.ToTable("Servidores", "recursoshumanos");
                });

            modelBuilder.Entity("Tensorroot.Gov.SharedKernel.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Error")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("OccurredOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ProcessedOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("ProcessedOnUtc");

                    b.ToTable("OutboxMessages", "recursoshumanos");
                });

            modelBuilder.Entity("Tensorroot.Gov.Modules.RecursosHumanos.Domain.Folha.FolhaDePagamento", b =>
                {
                    b.OwnsMany("Tensorroot.Gov.Modules.RecursosHumanos.Domain.Folha.EventoFolha", "Eventos", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<decimal>("BaseCalculo")
                                .HasColumnType("decimal(18,2)");

                            b1.Property<Guid>("FolhaDePagamentoId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("RegimePrevidenciario")
                                .IsRequired()
                                .HasMaxLength(10)
                                .HasColumnType("nvarchar(10)");

                            b1.Property<string>("Rubrica")
                                .IsRequired()
                                .HasMaxLength(30)
                                .HasColumnType("nvarchar(30)");

                            b1.Property<Guid>("ServidorId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Tipo")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("nvarchar(20)");

                            b1.Property<decimal>("Valor")
                                .HasColumnType("decimal(18,2)");

                            b1.HasKey("Id");

                            b1.HasIndex("FolhaDePagamentoId");

                            b1.ToTable("FolhasEventos", "recursoshumanos");

                            b1.WithOwner()
                                .HasForeignKey("FolhaDePagamentoId");
                        });

                    b.Navigation("Eventos");
                });

            modelBuilder.Entity("Tensorroot.Gov.Modules.RecursosHumanos.Domain.Servidores.Servidor", b =>
                {
                    b.OwnsMany("Tensorroot.Gov.Modules.RecursosHumanos.Domain.Servidores.Dependente", "Dependentes", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<DateOnly>("DataNascimento")
                                .HasColumnType("date");

                            b1.Property<string>("Nome")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("nvarchar(200)");

                            b1.Property<string>("Parentesco")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("nvarchar(50)");

                            b1.Property<Guid>("ServidorId")
                                .HasColumnType("uniqueidentifier");

                            b1.HasKey("Id");

                            b1.HasIndex("ServidorId");

                            b1.ToTable("ServidoresDependentes", "recursoshumanos");

                            b1.WithOwner()
                                .HasForeignKey("ServidorId");
                        });

                    b.Navigation("Dependentes");
                });
#pragma warning restore 612, 618
        }
    }
}
