// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Tensorroot.Gov.Modules.Administracao.Infrastructure.Persistence;

#nullable disable

namespace Tensorroot.Gov.Modules.Administracao.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AdministracaoDbContext))]
    [Migration("20260622181045_OutboxResiliencia")]
    partial class OutboxResiliencia
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("administracao")
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Tensorroot.Gov.BuildingBlocks.Infrastructure.Auditing.AuditTrail", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("AffectedColumns")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EntityId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EntityName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("IpAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NewValues")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OldValues")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("TimestampUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "TimestampUtc");

                    b.ToTable("AuditTrail", "administracao");
                });

            modelBuilder.Entity("Tensorroot.Gov.Modules.Administracao.Domain.Contratos.Contrato", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("DotacaoConfirmada")
                        .HasColumnType("bit");

                    b.Property<string>("EmpenhoRef")
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)")
                        .HasColumnName("EmpenhoRef");

                    b.Property<Guid>("FornecedorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("LicitacaoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("NumeroContratoPncp")
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("Objeto")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("OrigemContratacao")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<bool>("PublicadoNoPncp")
                        .HasColumnType("bit");

                    b.Property<string>("Situacao")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("ValorAtual")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ValorContratado")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateOnly>("VigenciaFim")
                        .HasColumnType("date");

                    b.Property<DateOnly>("VigenciaInicio")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "FornecedorId");

                    b.HasIndex("TenantId", "Situacao");

                    b.ToTable("Contratos", "administracao");
                });

            modelBuilder.Entity("Tensorroot.Gov.Modules.Administracao.Domain.Fornecedores.Fornecedor", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Cnpj")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("nvarchar(14)");

                    b.Property<string>("NivelCadastralSICAF")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("RazaoSocial")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Situacao")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "Cnpj")
                        .IsUnique();

                    b.ToTable("Fornecedores", "administracao");
                });

            modelBuilder.Entity("Tensorroot.Gov.Modules.Administracao.Domain.Licitacoes.Licitacao", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CriterioJulgamento")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<Guid?>("EtpId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Modalidade")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("NumeroEditalPncp")
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("Objeto")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<Guid?>("PropostaVencedoraId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Situacao")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("TermoReferenciaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("ValorEstimado")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "Situacao");

                    b.ToTable("Licitacoes", "administracao");
                });

            modelBuilder.Entity("Tensorroot.Gov.SharedKernel.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("int");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DeadLetteredOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Error")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("NextAttemptUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("OccurredOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ProcessedOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("ProcessedOnUtc", "DeadLetteredOnUtc", "NextAttemptUtc");

                    b.ToTable("OutboxMessages", "administracao");
                });

            modelBuilder.Entity("Tensorroot.Gov.Modules.Administracao.Domain.Contratos.Contrato", b =>
                {
                    b.OwnsMany("Tensorroot.Gov.Modules.Administracao.Domain.Contratos.Aditivo", "Aditivos", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<Guid>("ContratoId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<DateOnly>("DataCelebracao")
                                .HasColumnType("date");

                            b1.Property<string>("Justificativa")
                                .IsRequired()
                                .HasMaxLength(2000)
                                .HasColumnType("nvarchar(2000)");

                            b1.Property<DateOnly?>("NovaVigenciaFim")
                                .HasColumnType("date");

                            b1.Property<int>("Numero")
                                .HasColumnType("int");

                            b1.Property<decimal>("PercentualSobreValorOriginal")
                                .HasColumnType("decimal(9,4)");

                            b1.Property<bool>("PublicadoNoPncp")
                                .HasColumnType("bit");

                            b1.Property<string>("Tipo")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("nvarchar(20)");

                            b1.Property<decimal>("ValorDelta")
                                .HasColumnType("decimal(18,2)");

                            b1.HasKey("Id");

                            b1.HasIndex("ContratoId");

                            b1.ToTable("ContratosAditivos", "administracao");

                            b1.WithOwner()
                                .HasForeignKey("ContratoId");
                        });

                    b.OwnsMany("Tensorroot.Gov.Modules.Administracao.Domain.Contratos.Apostilamento", "Apostilamentos", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<Guid>("ContratoId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<DateOnly>("DataRegistro")
                                .HasColumnType("date");

                            b1.Property<string>("Descricao")
                                .IsRequired()
                                .HasMaxLength(2000)
                                .HasColumnType("nvarchar(2000)");

                            b1.Property<int>("Numero")
                                .HasColumnType("int");

                            b1.Property<string>("Tipo")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("nvarchar(20)");

                            b1.HasKey("Id");

                            b1.HasIndex("ContratoId");

                            b1.ToTable("ContratosApostilamentos", "administracao");

                            b1.WithOwner()
                                .HasForeignKey("ContratoId");
                        });

                    b.OwnsMany("Tensorroot.Gov.Modules.Administracao.Domain.Contratos.Garantia", "Garantias", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<Guid>("ContratoId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Modalidade")
                                .IsRequired()
                                .HasMaxLength(30)
                                .HasColumnType("nvarchar(30)");

                            b1.Property<decimal>("Percentual")
                                .HasColumnType("decimal(9,4)");

                            b1.Property<DateOnly>("ValidadeFim")
                                .HasColumnType("date");

                            b1.Property<decimal>("Valor")
                                .HasColumnType("decimal(18,2)");

                            b1.HasKey("Id");

                            b1.HasIndex("ContratoId");

                            b1.ToTable("ContratosGarantias", "administracao");

                            b1.WithOwner()
                                .HasForeignKey("ContratoId");
                        });

                    b.Navigation("Aditivos");

                    b.Navigation("Apostilamentos");

                    b.Navigation("Garantias");
                });

            modelBuilder.Entity("Tensorroot.Gov.Modules.Administracao.Domain.Fornecedores.Fornecedor", b =>
                {
                    b.OwnsMany("Tensorroot.Gov.Modules.Administracao.Domain.Fornecedores.Sancao", "Sancoes", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<DateOnly?>("DataFim")
                                .HasColumnType("date");

                            b1.Property<DateOnly>("DataInicio")
                                .HasColumnType("date");

                            b1.Property<Guid>("FornecedorId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Fundamentacao")
                                .IsRequired()
                                .HasMaxLength(2000)
                                .HasColumnType("nvarchar(2000)");

                            b1.Property<string>("ProcessoAdministrativo")
                                .IsRequired()
                                .HasMaxLength(60)
                                .HasColumnType("nvarchar(60)");

                            b1.Property<string>("Tipo")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("nvarchar(20)");

                            b1.Property<decimal?>("ValorMulta")
                                .HasColumnType("decimal(18,2)");

                            b1.HasKey("Id");

                            b1.HasIndex("FornecedorId");

                            b1.ToTable("FornecedoresSancoes", "administracao");

                            b1.WithOwner()
                                .HasForeignKey("FornecedorId");
                        });

                    b.Navigation("Sancoes");
                });

            modelBuilder.Entity("Tensorroot.Gov.Modules.Administracao.Domain.Licitacoes.Licitacao", b =>
                {
                    b.OwnsMany("Tensorroot.Gov.Modules.Administracao.Domain.Licitacoes.Habilitacao", "Habilitacoes", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<Guid>("FornecedorId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<Guid>("LicitacaoId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Motivo")
                                .HasMaxLength(2000)
                                .HasColumnType("nvarchar(2000)");

                            b1.Property<string>("Resultado")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("nvarchar(20)");

                            b1.HasKey("Id");

                            b1.HasIndex("LicitacaoId");

                            b1.ToTable("LicitacoesHabilitacoes", "administracao");

                            b1.WithOwner()
                                .HasForeignKey("LicitacaoId");
                        });

                    b.OwnsMany("Tensorroot.Gov.Modules.Administracao.Domain.Licitacoes.Lote", "Lotes", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Descricao")
                                .IsRequired()
                                .HasMaxLength(2000)
                                .HasColumnType("nvarchar(2000)");

                            b1.Property<Guid>("LicitacaoId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<int>("Numero")
                                .HasColumnType("int");

                            b1.Property<decimal>("ValorEstimado")
                                .HasColumnType("decimal(18,2)");

                            b1.HasKey("Id");

                            b1.HasIndex("LicitacaoId");

                            b1.ToTable("LicitacoesLotes", "administracao");

                            b1.WithOwner()
                                .HasForeignKey("LicitacaoId");
                        });

                    b.OwnsMany("Tensorroot.Gov.Modules.Administracao.Domain.Licitacoes.Proposta", "Propostas", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<int?>("Classificacao")
                                .HasColumnType("int");

                            b1.Property<Guid>("FornecedorId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<Guid>("LicitacaoId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<Guid>("LoteId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Situacao")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("nvarchar(20)");

                            b1.Property<decimal>("Valor")
                                .HasColumnType("decimal(18,2)");

                            b1.HasKey("Id");

                            b1.HasIndex("LicitacaoId");

                            b1.ToTable("LicitacoesPropostas", "administracao");

                            b1.WithOwner()
                                .HasForeignKey("LicitacaoId");
                        });

                    b.OwnsMany("Tensorroot.Gov.Modules.Administracao.Domain.Licitacoes.Recurso", "Recursos", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<DateOnly>("DataInterposicao")
                                .HasColumnType("date");

                            b1.Property<Guid>("FornecedorId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Fundamentacao")
                                .IsRequired()
                                .HasMaxLength(2000)
                                .HasColumnType("nvarchar(2000)");

                            b1.Property<Guid>("LicitacaoId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<bool?>("Provido")
                                .HasColumnType("bit");

                            b1.HasKey("Id");

                            b1.HasIndex("LicitacaoId");

                            b1.ToTable("LicitacoesRecursos", "administracao");

                            b1.WithOwner()
                                .HasForeignKey("LicitacaoId");
                        });

                    b.Navigation("Habilitacoes");

                    b.Navigation("Lotes");

                    b.Navigation("Propostas");

                    b.Navigation("Recursos");
                });
#pragma warning restore 612, 618
        }
    }
}
