// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Tensorroot.Gov.Modules.Transparencia.Infrastructure.Persistence;

#nullable disable

namespace Tensorroot.Gov.Modules.Transparencia.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(TransparenciaDbContext))]
    [Migration("20260622173112_AddRemessaProtocoloEZip")]
    partial class AddRemessaProtocoloEZip
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("transparencia")
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Tensorroot.Gov.BuildingBlocks.Infrastructure.Auditing.AuditTrail", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("AffectedColumns")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EntityId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EntityName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("IpAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NewValues")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OldValues")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("TimestampUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "TimestampUtc");

                    b.ToTable("AuditTrail", "transparencia");
                });

            modelBuilder.Entity("Tensorroot.Gov.Modules.Transparencia.Domain.DeclaracoesFiscais.DeclaracaoFiscal", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateOnly>("DataConsolidacao")
                        .HasColumnType("date");

                    b.Property<DateOnly>("DataLimite")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("DataTransmissao")
                        .HasColumnType("date");

                    b.Property<int>("Exercicio")
                        .HasColumnType("int");

                    b.Property<string>("MotivoRejeicao")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("ProtocoloSiconfi")
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("Situacao")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TipoDeclaracao")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "Exercicio", "TipoDeclaracao");

                    b.ToTable("DeclaracoesFiscais", "transparencia");
                });

            modelBuilder.Entity("Tensorroot.Gov.Modules.Transparencia.Domain.RemessasTce.RemessaTce", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateOnly?>("DataEnvio")
                        .HasColumnType("date");

                    b.Property<DateOnly>("DataGeracao")
                        .HasColumnType("date");

                    b.Property<DateOnly>("DataLimite")
                        .HasColumnType("date");

                    b.Property<string>("NomeArquivoZip")
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("ProtocoloTce")
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("Situacao")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("_alertaPrazoEmitido")
                        .HasColumnType("bit")
                        .HasColumnName("AlertaPrazoEmitido");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.ToTable("RemessasTce", "transparencia");
                });

            modelBuilder.Entity("Tensorroot.Gov.SharedKernel.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Error")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("OccurredOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ProcessedOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("ProcessedOnUtc");

                    b.ToTable("OutboxMessages", "transparencia");
                });

            modelBuilder.Entity("Tensorroot.Gov.Modules.Transparencia.Domain.DeclaracoesFiscais.DeclaracaoFiscal", b =>
                {
                    b.OwnsOne("Tensorroot.Gov.Modules.Transparencia.Domain.DeclaracoesFiscais.MatrizSaldos", "Matriz", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<Guid>("DeclaracaoFiscalId")
                                .HasColumnType("uniqueidentifier");

                            b1.HasKey("Id");

                            b1.HasIndex("DeclaracaoFiscalId")
                                .IsUnique();

                            b1.ToTable("DeclaracoesFiscaisMatrizes", "transparencia");

                            b1.WithOwner()
                                .HasForeignKey("DeclaracaoFiscalId");

                            b1.OwnsMany("Tensorroot.Gov.Modules.Transparencia.Domain.DeclaracoesFiscais.LinhaContabil", "Linhas", b2 =>
                                {
                                    b2.Property<Guid>("Id")
                                        .HasColumnType("uniqueidentifier");

                                    b2.Property<string>("ContaPcasp")
                                        .IsRequired()
                                        .HasMaxLength(30)
                                        .HasColumnType("nvarchar(30)");

                                    b2.Property<string>("InformacaoComplementar")
                                        .HasMaxLength(500)
                                        .HasColumnType("nvarchar(500)");

                                    b2.Property<Guid>("MatrizSaldosId")
                                        .HasColumnType("uniqueidentifier");

                                    b2.Property<string>("NaturezaSaldo")
                                        .IsRequired()
                                        .HasMaxLength(20)
                                        .HasColumnType("nvarchar(20)");

                                    b2.Property<decimal>("Valor")
                                        .HasColumnType("decimal(18,2)")
                                        .HasColumnName("Valor");

                                    b2.HasKey("Id");

                                    b2.HasIndex("MatrizSaldosId");

                                    b2.ToTable("DeclaracoesFiscaisLinhas", "transparencia");

                                    b2.WithOwner()
                                        .HasForeignKey("MatrizSaldosId");
                                });

                            b1.Navigation("Linhas");
                        });

                    b.OwnsOne("Tensorroot.Gov.Modules.Transparencia.Domain.ValueObjects.Bimestre", "Bimestre", b1 =>
                        {
                            b1.Property<Guid>("DeclaracaoFiscalId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<int>("Ano")
                                .HasColumnType("int")
                                .HasColumnName("BimestreAno");

                            b1.Property<int>("Numero")
                                .HasColumnType("int")
                                .HasColumnName("BimestreNumero");

                            b1.HasKey("DeclaracaoFiscalId");

                            b1.ToTable("DeclaracoesFiscais", "transparencia");

                            b1.WithOwner()
                                .HasForeignKey("DeclaracaoFiscalId");
                        });

                    b.OwnsOne("Tensorroot.Gov.Modules.Transparencia.Domain.ValueObjects.Competencia", "Competencia", b1 =>
                        {
                            b1.Property<Guid>("DeclaracaoFiscalId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<int>("Ano")
                                .HasColumnType("int")
                                .HasColumnName("CompetenciaAno");

                            b1.Property<int>("Mes")
                                .HasColumnType("int")
                                .HasColumnName("CompetenciaMes");

                            b1.HasKey("DeclaracaoFiscalId");

                            b1.ToTable("DeclaracoesFiscais", "transparencia");

                            b1.WithOwner()
                                .HasForeignKey("DeclaracaoFiscalId");
                        });

                    b.OwnsOne("Tensorroot.Gov.Modules.Transparencia.Domain.ValueObjects.Quadrimestre", "Quadrimestre", b1 =>
                        {
                            b1.Property<Guid>("DeclaracaoFiscalId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<int>("Ano")
                                .HasColumnType("int")
                                .HasColumnName("QuadrimestreAno");

                            b1.Property<int>("Numero")
                                .HasColumnType("int")
                                .HasColumnName("QuadrimestreNumero");

                            b1.HasKey("DeclaracaoFiscalId");

                            b1.ToTable("DeclaracoesFiscais", "transparencia");

                            b1.WithOwner()
                                .HasForeignKey("DeclaracaoFiscalId");
                        });

                    b.Navigation("Bimestre");

                    b.Navigation("Competencia");

                    b.Navigation("Matriz")
                        .IsRequired();

                    b.Navigation("Quadrimestre");
                });

            modelBuilder.Entity("Tensorroot.Gov.Modules.Transparencia.Domain.RemessasTce.RemessaTce", b =>
                {
                    b.OwnsMany("Tensorroot.Gov.Modules.Transparencia.Domain.RemessasTce.ArquivoRemessa", "Arquivos", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<byte[]>("Conteudo")
                                .IsRequired()
                                .HasColumnType("varbinary(max)");

                            b1.Property<string>("NomeArquivo")
                                .IsRequired()
                                .HasMaxLength(260)
                                .HasColumnType("nvarchar(260)");

                            b1.Property<Guid>("RemessaTceId")
                                .HasColumnType("uniqueidentifier");

                            b1.HasKey("Id");

                            b1.HasIndex("RemessaTceId");

                            b1.ToTable("RemessasTceArquivos", "transparencia");

                            b1.WithOwner()
                                .HasForeignKey("RemessaTceId");

                            b1.OwnsOne("Tensorroot.Gov.Modules.Transparencia.Domain.RemessasTce.HashIntegridade", "Hash", b2 =>
                                {
                                    b2.Property<Guid>("ArquivoRemessaId")
                                        .HasColumnType("uniqueidentifier");

                                    b2.Property<string>("Algoritmo")
                                        .IsRequired()
                                        .HasMaxLength(20)
                                        .HasColumnType("nvarchar(20)")
                                        .HasColumnName("HashAlgoritmo");

                                    b2.Property<string>("Valor")
                                        .IsRequired()
                                        .HasMaxLength(128)
                                        .HasColumnType("nvarchar(128)")
                                        .HasColumnName("HashValor");

                                    b2.HasKey("ArquivoRemessaId");

                                    b2.ToTable("RemessasTceArquivos", "transparencia");

                                    b2.WithOwner()
                                        .HasForeignKey("ArquivoRemessaId");
                                });

                            b1.OwnsMany("Tensorroot.Gov.Modules.Transparencia.Domain.RemessasTce.RegistroLeiaute", "Registros", b2 =>
                                {
                                    b2.Property<Guid>("Id")
                                        .HasColumnType("uniqueidentifier");

                                    b2.Property<Guid>("ArquivoRemessaId")
                                        .HasColumnType("uniqueidentifier");

                                    b2.Property<string>("Conteudo")
                                        .IsRequired()
                                        .HasColumnType("nvarchar(max)");

                                    b2.Property<string>("Tipo")
                                        .IsRequired()
                                        .HasMaxLength(40)
                                        .HasColumnType("nvarchar(40)");

                                    b2.HasKey("Id");

                                    b2.HasIndex("ArquivoRemessaId");

                                    b2.ToTable("RemessasTceRegistros", "transparencia");

                                    b2.WithOwner()
                                        .HasForeignKey("ArquivoRemessaId");
                                });

                            b1.Navigation("Hash")
                                .IsRequired();

                            b1.Navigation("Registros");
                        });

                    b.OwnsOne("Tensorroot.Gov.Modules.Transparencia.Domain.RemessasTce.Leiaute", "Leiaute", b1 =>
                        {
                            b1.Property<Guid>("RemessaTceId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Codigo")
                                .IsRequired()
                                .HasMaxLength(40)
                                .HasColumnType("nvarchar(40)")
                                .HasColumnName("LeiauteCodigo");

                            b1.Property<string>("Versao")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("nvarchar(20)")
                                .HasColumnName("LeiauteVersao");

                            b1.HasKey("RemessaTceId");

                            b1.ToTable("RemessasTce", "transparencia");

                            b1.WithOwner()
                                .HasForeignKey("RemessaTceId");
                        });

                    b.OwnsOne("Tensorroot.Gov.Modules.Transparencia.Domain.RemessasTce.Periodo", "Periodo", b1 =>
                        {
                            b1.Property<Guid>("RemessaTceId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<int>("Exercicio")
                                .HasColumnType("int")
                                .HasColumnName("Exercicio");

                            b1.Property<int>("Numero")
                                .HasColumnType("int")
                                .HasColumnName("PeriodoNumero");

                            b1.Property<string>("Tipo")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("nvarchar(20)")
                                .HasColumnName("PeriodoTipo");

                            b1.HasKey("RemessaTceId");

                            b1.ToTable("RemessasTce", "transparencia");

                            b1.WithOwner()
                                .HasForeignKey("RemessaTceId");
                        });

                    b.OwnsOne("Tensorroot.Gov.Modules.Transparencia.Domain.RemessasTce.HashIntegridade", "HashIntegridade", b1 =>
                        {
                            b1.Property<Guid>("RemessaTceId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Algoritmo")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("nvarchar(20)")
                                .HasColumnName("HashAlgoritmo");

                            b1.Property<string>("Valor")
                                .IsRequired()
                                .HasMaxLength(128)
                                .HasColumnType("nvarchar(128)")
                                .HasColumnName("HashValor");

                            b1.HasKey("RemessaTceId");

                            b1.ToTable("RemessasTce", "transparencia");

                            b1.WithOwner()
                                .HasForeignKey("RemessaTceId");
                        });

                    b.OwnsOne("Tensorroot.Gov.Modules.Transparencia.Domain.RemessasTce.ResultadoValidacao", "ResultadoValidacao", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("LeiauteVersao")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("nvarchar(20)");

                            b1.Property<bool>("PossuiErro")
                                .HasColumnType("bit");

                            b1.Property<int>("QuantidadeAvisos")
                                .HasColumnType("int");

                            b1.Property<int>("QuantidadeErros")
                                .HasColumnType("int");

                            b1.Property<Guid>("RemessaTceId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<DateTimeOffset>("ValidadoEm")
                                .HasColumnType("datetimeoffset");

                            b1.HasKey("Id");

                            b1.HasIndex("RemessaTceId")
                                .IsUnique();

                            b1.ToTable("RemessasTceResultadosValidacao", "transparencia");

                            b1.WithOwner()
                                .HasForeignKey("RemessaTceId");

                            b1.OwnsMany("Tensorroot.Gov.Modules.Transparencia.Domain.RemessasTce.OcorrenciaValidacao", "Ocorrencias", b2 =>
                                {
                                    b2.Property<Guid>("Id")
                                        .HasColumnType("uniqueidentifier");

                                    b2.Property<string>("Arquivo")
                                        .IsRequired()
                                        .HasMaxLength(260)
                                        .HasColumnType("nvarchar(260)");

                                    b2.Property<int>("Linha")
                                        .HasColumnType("int");

                                    b2.Property<string>("Mensagem")
                                        .IsRequired()
                                        .HasMaxLength(1000)
                                        .HasColumnType("nvarchar(1000)");

                                    b2.Property<Guid>("ResultadoValidacaoId")
                                        .HasColumnType("uniqueidentifier");

                                    b2.Property<string>("Severidade")
                                        .IsRequired()
                                        .HasMaxLength(20)
                                        .HasColumnType("nvarchar(20)");

                                    b2.HasKey("Id");

                                    b2.HasIndex("ResultadoValidacaoId");

                                    b2.ToTable("RemessasTceOcorrenciasValidacao", "transparencia");

                                    b2.WithOwner()
                                        .HasForeignKey("ResultadoValidacaoId");
                                });

                            b1.Navigation("Ocorrencias");
                        });

                    b.Navigation("Arquivos");

                    b.Navigation("HashIntegridade");

                    b.Navigation("Leiaute")
                        .IsRequired();

                    b.Navigation("Periodo")
                        .IsRequired();

                    b.Navigation("ResultadoValidacao");
                });
#pragma warning restore 612, 618
        }
    }
}
