// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Tensorroot.Gov.Modules.Patrimonio.Infrastructure.Persistence;

#nullable disable

namespace Tensorroot.Gov.Modules.Patrimonio.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(PatrimonioDbContext))]
    partial class PatrimonioDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("patrimonio")
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Tensorroot.Gov.BuildingBlocks.Infrastructure.Auditing.AuditTrail", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("AffectedColumns")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EntityId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EntityName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("HashAnterior")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("HashAtual")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("IpAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NewValues")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OldValues")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("Sequencia")
                        .HasColumnType("bigint");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("TimestampUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "Sequencia");

                    b.HasIndex("TenantId", "TimestampUtc");

                    b.ToTable("AuditTrail", "patrimonio");
                });

            modelBuilder.Entity("Tensorroot.Gov.Modules.Patrimonio.Domain.Bens.BemPatrimonial", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateOnly>("DataIncorporacao")
                        .HasColumnType("date");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("EmCondicoesDeUso")
                        .HasColumnType("bit");

                    b.Property<string>("NumeroTombamento")
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("Situacao")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("TombamentoBusca")
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<decimal>("ValorContabil")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ValorInicial")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ValorResidual")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ValorTerreno")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("VidaUtilMeses")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "NumeroTombamento");

                    b.HasIndex("TenantId", "TombamentoBusca");

                    b.ToTable("Bens", "patrimonio");
                });

            modelBuilder.Entity("Tensorroot.Gov.Modules.Patrimonio.Domain.Estoque.ItemEstoque", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ClassificacaoAbc")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<decimal>("CustoMedio")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("MetodoCusteio")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<decimal>("PontoPedido")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Saldo")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Situacao")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("UnidadeMedida")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<decimal?>("ValorRealizavelLiquido")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "Codigo")
                        .IsUnique();

                    b.ToTable("ItensEstoque", "patrimonio");
                });

            modelBuilder.Entity("Tensorroot.Gov.Modules.Patrimonio.Domain.Frota.Veiculo", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateOnly>("DataIncorporacao")
                        .HasColumnType("date");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("EmCondicoesDeUso")
                        .HasColumnType("bit");

                    b.Property<decimal>("Horimetro")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid?>("MotoristaAtualId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("NumeroTombamento")
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<int>("Odometro")
                        .HasColumnType("int");

                    b.Property<string>("Origem")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Placa")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("nvarchar(7)");

                    b.Property<string>("PlacaBusca")
                        .HasMaxLength(7)
                        .HasColumnType("nvarchar(7)");

                    b.Property<string>("Renavam")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)");

                    b.Property<string>("RenavamBusca")
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)");

                    b.Property<string>("Situacao")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("ValorContabil")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ValorInicial")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ValorResidual")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("VidaUtilMeses")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "PlacaBusca");

                    b.HasIndex("TenantId", "Renavam")
                        .IsUnique();

                    b.HasIndex("TenantId", "RenavamBusca");

                    b.ToTable("Veiculos", "patrimonio");
                });

            modelBuilder.Entity("Tensorroot.Gov.Modules.Patrimonio.Domain.Inventarios.Inventario", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateOnly>("DataAbertura")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("DataEncerramento")
                        .HasColumnType("date");

                    b.Property<int>("Exercicio")
                        .HasColumnType("int");

                    b.Property<string>("Portaria")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Setor")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Situacao")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "Exercicio", "Tipo", "Setor");

                    b.ToTable("Inventarios", "patrimonio");
                });

            modelBuilder.Entity("Tensorroot.Gov.SharedKernel.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("int");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DeadLetteredOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Error")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("NextAttemptUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("OccurredOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ProcessedOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("ProcessedOnUtc", "DeadLetteredOnUtc", "NextAttemptUtc");

                    b.ToTable("OutboxMessages", "patrimonio");
                });

            modelBuilder.Entity("Tensorroot.Gov.Modules.Patrimonio.Domain.Bens.BemPatrimonial", b =>
                {
                    b.OwnsMany("Tensorroot.Gov.Modules.Patrimonio.Domain.Bens.HistoricoDepreciacao", "HistoricosDepreciacao", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<Guid>("BemPatrimonialId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<DateOnly>("Competencia")
                                .HasColumnType("date");

                            b1.Property<decimal>("ValorContabilResultante")
                                .HasColumnType("decimal(18,2)");

                            b1.Property<decimal>("ValorDepreciado")
                                .HasColumnType("decimal(18,2)");

                            b1.HasKey("Id");

                            b1.HasIndex("BemPatrimonialId");

                            b1.ToTable("BensHistoricosDepreciacao", "patrimonio");

                            b1.WithOwner()
                                .HasForeignKey("BemPatrimonialId");
                        });

                    b.OwnsMany("Tensorroot.Gov.Modules.Patrimonio.Domain.Bens.Impairment", "Impairments", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<Guid>("BemPatrimonialId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<DateOnly>("Data")
                                .HasColumnType("date");

                            b1.Property<string>("LaudoUri")
                                .IsRequired()
                                .HasMaxLength(500)
                                .HasColumnType("nvarchar(500)");

                            b1.Property<decimal>("PerdaReconhecida")
                                .HasColumnType("decimal(18,2)");

                            b1.Property<decimal>("ValorRecuperavel")
                                .HasColumnType("decimal(18,2)");

                            b1.HasKey("Id");

                            b1.HasIndex("BemPatrimonialId");

                            b1.ToTable("BensImpairments", "patrimonio");

                            b1.WithOwner()
                                .HasForeignKey("BemPatrimonialId");
                        });

                    b.OwnsMany("Tensorroot.Gov.Modules.Patrimonio.Domain.Bens.MovimentacaoPatrimonial", "Movimentacoes", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<Guid>("BemPatrimonialId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<DateOnly>("Data")
                                .HasColumnType("date");

                            b1.Property<string>("LocalizacaoDestino")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("nvarchar(200)");

                            b1.Property<string>("LocalizacaoOrigem")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("nvarchar(200)");

                            b1.Property<Guid>("ResponsavelId")
                                .HasColumnType("uniqueidentifier");

                            b1.HasKey("Id");

                            b1.HasIndex("BemPatrimonialId");

                            b1.ToTable("BensMovimentacoes", "patrimonio");

                            b1.WithOwner()
                                .HasForeignKey("BemPatrimonialId");
                        });

                    b.OwnsMany("Tensorroot.Gov.Modules.Patrimonio.Domain.Bens.Reavaliacao", "Reavaliacoes", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<Guid>("BemPatrimonialId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<DateOnly>("Data")
                                .HasColumnType("date");

                            b1.Property<string>("LaudoUri")
                                .IsRequired()
                                .HasMaxLength(500)
                                .HasColumnType("nvarchar(500)");

                            b1.Property<decimal>("NovoValorJusto")
                                .HasColumnType("decimal(18,2)");

                            b1.HasKey("Id");

                            b1.HasIndex("BemPatrimonialId");

                            b1.ToTable("BensReavaliacoes", "patrimonio");

                            b1.WithOwner()
                                .HasForeignKey("BemPatrimonialId");
                        });

                    b.Navigation("HistoricosDepreciacao");

                    b.Navigation("Impairments");

                    b.Navigation("Movimentacoes");

                    b.Navigation("Reavaliacoes");
                });

            modelBuilder.Entity("Tensorroot.Gov.Modules.Patrimonio.Domain.Estoque.ItemEstoque", b =>
                {
                    b.OwnsMany("Tensorroot.Gov.Modules.Patrimonio.Domain.Estoque.Lote", "Lotes", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<decimal>("CustoUnitario")
                                .HasColumnType("decimal(18,2)");

                            b1.Property<DateOnly>("DataEntrada")
                                .HasColumnType("date");

                            b1.Property<Guid>("ItemEstoqueId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<decimal>("QuantidadeEntrada")
                                .HasColumnType("decimal(18,2)");

                            b1.Property<decimal>("QuantidadeRestante")
                                .HasColumnType("decimal(18,2)");

                            b1.Property<DateOnly?>("Validade")
                                .HasColumnType("date");

                            b1.HasKey("Id");

                            b1.HasIndex("ItemEstoqueId");

                            b1.ToTable("ItensEstoqueLotes", "patrimonio");

                            b1.WithOwner()
                                .HasForeignKey("ItemEstoqueId");
                        });

                    b.OwnsMany("Tensorroot.Gov.Modules.Patrimonio.Domain.Estoque.MovimentoEstoque", "Movimentos", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<DateOnly>("Data")
                                .HasColumnType("date");

                            b1.Property<string>("Documento")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)");

                            b1.Property<Guid>("ItemEstoqueId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<decimal>("Quantidade")
                                .HasColumnType("decimal(18,2)");

                            b1.Property<string>("Tipo")
                                .IsRequired()
                                .HasMaxLength(10)
                                .HasColumnType("nvarchar(10)");

                            b1.Property<decimal>("ValorUnitario")
                                .HasColumnType("decimal(18,2)");

                            b1.HasKey("Id");

                            b1.HasIndex("ItemEstoqueId");

                            b1.ToTable("ItensEstoqueMovimentos", "patrimonio");

                            b1.WithOwner()
                                .HasForeignKey("ItemEstoqueId");
                        });

                    b.OwnsMany("Tensorroot.Gov.Modules.Patrimonio.Domain.Estoque.Requisicao", "Requisicoes", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<DateOnly>("Data")
                                .HasColumnType("date");

                            b1.Property<Guid>("ItemEstoqueId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<decimal>("Quantidade")
                                .HasColumnType("decimal(18,2)");

                            b1.Property<string>("Situacao")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("nvarchar(20)");

                            b1.Property<Guid>("SolicitanteId")
                                .HasColumnType("uniqueidentifier");

                            b1.HasKey("Id");

                            b1.HasIndex("ItemEstoqueId");

                            b1.ToTable("ItensEstoqueRequisicoes", "patrimonio");

                            b1.WithOwner()
                                .HasForeignKey("ItemEstoqueId");
                        });

                    b.Navigation("Lotes");

                    b.Navigation("Movimentos");

                    b.Navigation("Requisicoes");
                });

            modelBuilder.Entity("Tensorroot.Gov.Modules.Patrimonio.Domain.Frota.Veiculo", b =>
                {
                    b.OwnsMany("Tensorroot.Gov.Modules.Patrimonio.Domain.Frota.Abastecimento", "Abastecimentos", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<DateOnly>("Data")
                                .HasColumnType("date");

                            b1.Property<decimal>("Horimetro")
                                .HasColumnType("decimal(18,2)");

                            b1.Property<decimal>("Litros")
                                .HasColumnType("decimal(18,2)");

                            b1.Property<Guid?>("MotoristaId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<int>("Odometro")
                                .HasColumnType("int");

                            b1.Property<decimal>("Valor")
                                .HasColumnType("decimal(18,2)");

                            b1.Property<Guid>("VeiculoId")
                                .HasColumnType("uniqueidentifier");

                            b1.HasKey("Id");

                            b1.HasIndex("VeiculoId");

                            b1.ToTable("VeiculosAbastecimentos", "patrimonio");

                            b1.WithOwner()
                                .HasForeignKey("VeiculoId");
                        });

                    b.OwnsMany("Tensorroot.Gov.Modules.Patrimonio.Domain.Frota.Licenciamento", "Licenciamentos", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<DateOnly>("Data")
                                .HasColumnType("date");

                            b1.Property<int>("Exercicio")
                                .HasColumnType("int");

                            b1.Property<string>("Situacao")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("nvarchar(20)");

                            b1.Property<decimal>("ValorIpva")
                                .HasColumnType("decimal(18,2)");

                            b1.Property<decimal>("ValorTaxa")
                                .HasColumnType("decimal(18,2)");

                            b1.Property<Guid>("VeiculoId")
                                .HasColumnType("uniqueidentifier");

                            b1.HasKey("Id");

                            b1.HasIndex("VeiculoId");

                            b1.ToTable("VeiculosLicenciamentos", "patrimonio");

                            b1.WithOwner()
                                .HasForeignKey("VeiculoId");
                        });

                    b.OwnsMany("Tensorroot.Gov.Modules.Patrimonio.Domain.Frota.ManutencaoOS", "OrdensServico", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<decimal>("CustoEstimado")
                                .HasColumnType("decimal(18,2)");

                            b1.Property<decimal?>("CustoRealizado")
                                .HasColumnType("decimal(18,2)");

                            b1.Property<DateOnly?>("DataConclusao")
                                .HasColumnType("date");

                            b1.Property<string>("Descricao")
                                .IsRequired()
                                .HasMaxLength(500)
                                .HasColumnType("nvarchar(500)");

                            b1.Property<int>("Odometro")
                                .HasColumnType("int");

                            b1.Property<string>("Situacao")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("nvarchar(20)");

                            b1.Property<Guid>("VeiculoId")
                                .HasColumnType("uniqueidentifier");

                            b1.HasKey("Id");

                            b1.HasIndex("VeiculoId");

                            b1.ToTable("VeiculosOrdensServico", "patrimonio");

                            b1.WithOwner()
                                .HasForeignKey("VeiculoId");
                        });

                    b.OwnsMany("Tensorroot.Gov.Modules.Patrimonio.Domain.Frota.Motorista", "Motoristas", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("CategoriaCnh")
                                .IsRequired()
                                .HasMaxLength(5)
                                .HasColumnType("nvarchar(5)");

                            b1.Property<string>("Cnh")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("nvarchar(20)");

                            b1.Property<string>("Nome")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("nvarchar(200)");

                            b1.Property<DateOnly>("ValidadeCnh")
                                .HasColumnType("date");

                            b1.Property<Guid>("VeiculoId")
                                .HasColumnType("uniqueidentifier");

                            b1.HasKey("Id");

                            b1.HasIndex("VeiculoId");

                            b1.ToTable("VeiculosMotoristas", "patrimonio");

                            b1.WithOwner()
                                .HasForeignKey("VeiculoId");
                        });

                    b.OwnsMany("Tensorroot.Gov.Modules.Patrimonio.Domain.Frota.Multa", "Multas", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("CodigoInfracaoCtb")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("nvarchar(20)");

                            b1.Property<DateOnly>("DataInfracao")
                                .HasColumnType("date");

                            b1.Property<Guid?>("MotoristaId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Situacao")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("nvarchar(20)");

                            b1.Property<decimal>("Valor")
                                .HasColumnType("decimal(18,2)");

                            b1.Property<Guid>("VeiculoId")
                                .HasColumnType("uniqueidentifier");

                            b1.HasKey("Id");

                            b1.HasIndex("VeiculoId");

                            b1.ToTable("VeiculosMultas", "patrimonio");

                            b1.WithOwner()
                                .HasForeignKey("VeiculoId");
                        });

                    b.OwnsMany("Tensorroot.Gov.Modules.Patrimonio.Domain.Bens.HistoricoDepreciacao", "HistoricosDepreciacao", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<DateOnly>("Competencia")
                                .HasColumnType("date");

                            b1.Property<decimal>("ValorContabilResultante")
                                .HasColumnType("decimal(18,2)");

                            b1.Property<decimal>("ValorDepreciado")
                                .HasColumnType("decimal(18,2)");

                            b1.Property<Guid>("VeiculoId")
                                .HasColumnType("uniqueidentifier");

                            b1.HasKey("Id");

                            b1.HasIndex("VeiculoId");

                            b1.ToTable("VeiculosHistoricosDepreciacao", "patrimonio");

                            b1.WithOwner()
                                .HasForeignKey("VeiculoId");
                        });

                    b.Navigation("Abastecimentos");

                    b.Navigation("HistoricosDepreciacao");

                    b.Navigation("Licenciamentos");

                    b.Navigation("Motoristas");

                    b.Navigation("Multas");

                    b.Navigation("OrdensServico");
                });

            modelBuilder.Entity("Tensorroot.Gov.Modules.Patrimonio.Domain.Inventarios.Inventario", b =>
                {
                    b.OwnsMany("Tensorroot.Gov.Modules.Patrimonio.Domain.Inventarios.MembroComissao", "Comissao", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<Guid>("InventarioId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Nome")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("nvarchar(200)");

                            b1.Property<bool>("Presidente")
                                .HasColumnType("bit");

                            b1.Property<Guid>("ResponsavelId")
                                .HasColumnType("uniqueidentifier");

                            b1.HasKey("Id");

                            b1.HasIndex("InventarioId");

                            b1.ToTable("InventariosComissao", "patrimonio");

                            b1.WithOwner()
                                .HasForeignKey("InventarioId");
                        });

                    b.OwnsMany("Tensorroot.Gov.Modules.Patrimonio.Domain.Inventarios.ItemInventario", "Itens", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<Guid>("BemPatrimonialId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<bool>("Contado")
                                .HasColumnType("bit");

                            b1.Property<string>("DescricaoSnapshot")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("nvarchar(200)");

                            b1.Property<Guid>("InventarioId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("LocalizacaoEncontrada")
                                .HasMaxLength(200)
                                .HasColumnType("nvarchar(200)");

                            b1.Property<string>("LocalizacaoEsperada")
                                .HasMaxLength(200)
                                .HasColumnType("nvarchar(200)");

                            b1.Property<string>("NumeroTombamento")
                                .HasMaxLength(40)
                                .HasColumnType("nvarchar(40)");

                            b1.Property<string>("Observacao")
                                .HasMaxLength(500)
                                .HasColumnType("nvarchar(500)");

                            b1.Property<string>("SituacaoEncontrada")
                                .HasMaxLength(30)
                                .HasColumnType("nvarchar(30)");

                            b1.Property<decimal>("ValorContabilSnapshot")
                                .HasColumnType("decimal(18,2)");

                            b1.HasKey("Id");

                            b1.HasIndex("InventarioId");

                            b1.ToTable("InventariosItens", "patrimonio");

                            b1.WithOwner()
                                .HasForeignKey("InventarioId");
                        });

                    b.OwnsMany("Tensorroot.Gov.Modules.Patrimonio.Domain.Inventarios.DivergenciaInventario", "Divergencias", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<Guid?>("BemPatrimonialId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Descricao")
                                .IsRequired()
                                .HasMaxLength(1000)
                                .HasColumnType("nvarchar(1000)");

                            b1.Property<Guid>("InventarioId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Recomendacao")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("nvarchar(20)");

                            b1.Property<string>("Tipo")
                                .IsRequired()
                                .HasMaxLength(30)
                                .HasColumnType("nvarchar(30)");

                            b1.HasKey("Id");

                            b1.HasIndex("InventarioId");

                            b1.ToTable("InventariosDivergencias", "patrimonio");

                            b1.WithOwner()
                                .HasForeignKey("InventarioId");
                        });

                    b.Navigation("Comissao");

                    b.Navigation("Divergencias");

                    b.Navigation("Itens");
                });
#pragma warning restore 612, 618
        }
    }
}
