<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="../Tensorroot.Gov.Modules.Protocolo.Domain/Tensorroot.Gov.Modules.Protocolo.Domain.csproj" />
    <ProjectReference Include="../Tensorroot.Gov.Modules.Protocolo.Contracts/Tensorroot.Gov.Modules.Protocolo.Contracts.csproj" />
    <ProjectReference Include="../../../BuildingBlocks/Tensorroot.Gov.BuildingBlocks.Application/Tensorroot.Gov.BuildingBlocks.Application.csproj" />
  </ItemGroup>
</Project>
