// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Tensorroot.Gov.Modules.Tributos.Infrastructure.Persistence;

#nullable disable

namespace Tensorroot.Gov.Modules.Tributos.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(TributosDbContext))]
    [Migration("20260624002538_P0AuditHashChainSync")]
    partial class P0AuditHashChainSync
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("tributos")
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Tensorroot.Gov.BuildingBlocks.Infrastructure.Auditing.AuditTrail", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("AffectedColumns")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EntityId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EntityName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("HashAnterior")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("HashAtual")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("IpAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NewValues")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OldValues")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("Sequencia")
                        .HasColumnType("bigint");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("TimestampUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "Sequencia")
                        .IsUnique()
                        .HasFilter("[Sequencia] > 0");

                    b.HasIndex("TenantId", "TimestampUtc");

                    b.ToTable("AuditTrail", "tributos");
                });

            modelBuilder.Entity("Tensorroot.Gov.Modules.Tributos.Domain.Alvaras.Alvara", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AtividadeCnae")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<Guid>("ContribuinteId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Especie")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<DateOnly>("FimVigencia")
                        .HasColumnType("date");

                    b.Property<Guid?>("ImovelId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateOnly>("InicioVigencia")
                        .HasColumnType("date");

                    b.Property<string>("NomeEstabelecimento")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Situacao")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "ContribuinteId");

                    b.ToTable("Alvaras", "tributos");
                });

            modelBuilder.Entity("Tensorroot.Gov.Modules.Tributos.Domain.Arrecadacao.Dam", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ContribuinteId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("LancamentoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("ValorTotal")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "LancamentoId");

                    b.ToTable("Dams", "tributos");
                });

            modelBuilder.Entity("Tensorroot.Gov.Modules.Tributos.Domain.Arrecadacao.Parcela", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("DamId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateOnly?>("DataPagamento")
                        .HasColumnType("date");

                    b.Property<int>("Numero")
                        .HasColumnType("int");

                    b.Property<bool>("Paga")
                        .HasColumnType("bit");

                    b.Property<decimal>("Valor")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateOnly>("Vencimento")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("DamId");

                    b.ToTable("Parcelas", "tributos");
                });

            modelBuilder.Entity("Tensorroot.Gov.Modules.Tributos.Domain.Contribuintes.Contribuinte", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Documento")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("nvarchar(14)");

                    b.Property<string>("InscricaoMunicipal")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TipoPessoa")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "Documento");

                    b.ToTable("Contribuintes", "tributos");
                });

            modelBuilder.Entity("Tensorroot.Gov.Modules.Tributos.Domain.Cosip.FaixaCosip", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Classe")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<decimal?>("ConsumoMaximoKwh")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("ConsumoMinimoKwh")
                        .HasColumnType("decimal(18,4)");

                    b.Property<Guid>("TabelaCosipId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Valor")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("TabelaCosipId");

                    b.ToTable("FaixasCosip", "tributos");
                });

            modelBuilder.Entity("Tensorroot.Gov.Modules.Tributos.Domain.Cosip.TabelaCosip", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Exercicio")
                        .HasColumnType("int");

                    b.Property<string>("FundamentoLegal")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Vigente")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "Exercicio");

                    b.ToTable("TabelasCosip", "tributos");
                });

            modelBuilder.Entity("Tensorroot.Gov.Modules.Tributos.Domain.Dividas.DividaAtiva", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AnosPrescricaoParametrizado")
                        .HasColumnType("int");

                    b.Property<Guid>("ContribuinteId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateOnly>("DataConstituicaoDefinitiva")
                        .HasColumnType("date");

                    b.Property<DateOnly>("DataInscricao")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("DataUltimaInterrupcaoPrescricao")
                        .HasColumnType("date");

                    b.Property<string>("FundamentoLegal")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<Guid>("LancamentoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("NumeroCda")
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<long>("NumeroInscricao")
                        .HasColumnType("bigint");

                    b.Property<string>("OrigemNatureza")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Situacao")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TipoTributo")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<decimal>("ValorOriginario")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateOnly>("VencimentoOrigem")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "ContribuinteId");

                    b.HasIndex("TenantId", "NumeroInscricao")
                        .IsUnique();

                    b.ToTable("DividasAtivas", "tributos");
                });

            modelBuilder.Entity("Tensorroot.Gov.Modules.Tributos.Domain.Dividas.RemessaProtesto", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateOnly>("DataGeracao")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("DataRetorno")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("DataTransmissao")
                        .HasColumnType("date");

                    b.Property<Guid>("DividaAtivaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("IdentificadorCra")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("NumeroCda")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("Ocorrencia")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("ProtocoloCartorio")
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("Situacao")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("DividaAtivaId");

                    b.ToTable("RemessasProtesto", "tributos");
                });

            modelBuilder.Entity("Tensorroot.Gov.Modules.Tributos.Domain.Imoveis.Imovel", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<Guid>("ProprietarioId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "ProprietarioId");

                    b.ToTable("Imoveis", "tributos");
                });

            modelBuilder.Entity("Tensorroot.Gov.Modules.Tributos.Domain.Iss.ApuracaoIss", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Competencia")
                        .HasColumnType("int");

                    b.Property<Guid>("ContribuinteId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("IssProprio")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("IssRetido")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("IssSubstituicao")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "ContribuinteId", "Competencia")
                        .IsUnique();

                    b.ToTable("ApuracoesIss", "tributos");
                });

            modelBuilder.Entity("Tensorroot.Gov.Modules.Tributos.Domain.Iss.ItemAliquotaIss", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("AliquotaPercentual")
                        .HasColumnType("decimal(9,4)");

                    b.Property<string>("ItemListaServico")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<bool>("RetencaoObrigatoria")
                        .HasColumnType("bit");

                    b.Property<bool>("SubstituicaoTributaria")
                        .HasColumnType("bit");

                    b.Property<Guid>("TabelaAliquotaIssId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("TabelaAliquotaIssId");

                    b.ToTable("ItensAliquotaIss", "tributos");
                });

            modelBuilder.Entity("Tensorroot.Gov.Modules.Tributos.Domain.Iss.ItemApuracaoIss", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("AliquotaPercentual")
                        .HasColumnType("decimal(9,4)");

                    b.Property<Guid>("ApuracaoIssId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("BaseCalculo")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ChaveAcesso")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<decimal>("IssApurado")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ItemListaServico")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Modalidade")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.HasIndex("ApuracaoIssId");

                    b.ToTable("ItensApuracaoIss", "tributos");
                });

            modelBuilder.Entity("Tensorroot.Gov.Modules.Tributos.Domain.Iss.TabelaAliquotaIss", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("FundamentoLegal")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("VigenciaInicioAaaaMm")
                        .HasColumnType("int");

                    b.Property<bool>("Vigente")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "VigenciaInicioAaaaMm");

                    b.ToTable("TabelasAliquotaIss", "tributos");
                });

            modelBuilder.Entity("Tensorroot.Gov.Modules.Tributos.Domain.Itbi.AliquotaItbi", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("AliquotaGeralPercentual")
                        .HasColumnType("decimal(9,4)");

                    b.Property<decimal>("AliquotaSfhFinanciadaPercentual")
                        .HasColumnType("decimal(9,4)");

                    b.Property<int>("Exercicio")
                        .HasColumnType("int");

                    b.Property<string>("FundamentoLegal")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Vigente")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "Exercicio");

                    b.ToTable("AliquotasItbi", "tributos");
                });

            modelBuilder.Entity("Tensorroot.Gov.Modules.Tributos.Domain.Itbi.Arbitramento.ProcessoArbitramentoItbi", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateOnly?>("DataAberturaContraditorio")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("DataApresentacaoContraditorio")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("DataDesfecho")
                        .HasColumnType("date");

                    b.Property<DateOnly>("DataInstauracao")
                        .HasColumnType("date");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("FundamentacaoFisco")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<string>("JustificativaContribuinte")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<string>("MotivoInstauracao")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("NumeroProcesso")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<Guid>("ResponsavelId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TransmissaoImobiliariaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal?>("ValorArbitradoFinal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ValorPropostoFisco")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "NumeroProcesso")
                        .IsUnique();

                    b.HasIndex("TenantId", "TransmissaoImobiliariaId");

                    b.ToTable("ProcessosArbitramentoItbi", "tributos");
                });

            modelBuilder.Entity("Tensorroot.Gov.Modules.Tributos.Domain.Itbi.TransmissaoImobiliaria", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AdquirenteId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("AliquotaPercentual")
                        .HasColumnType("decimal(9,4)");

                    b.Property<decimal>("BaseCalculo")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Exercicio")
                        .HasColumnType("int");

                    b.Property<Guid>("ImovelId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("ImpostoDevido")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Origem")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<Guid?>("ProcessoArbitramentoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TransmitenteId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("ValorDeclarado")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ValorVenalReferencia")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "ImovelId");

                    b.ToTable("TransmissoesImobiliarias", "tributos");
                });

            modelBuilder.Entity("Tensorroot.Gov.Modules.Tributos.Domain.Lancamentos.Lancamento", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Competencia")
                        .HasColumnType("int");

                    b.Property<Guid>("ContribuinteId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ImovelId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Situacao")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TipoTributo")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<decimal>("ValorPrincipal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateOnly>("Vencimento")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("ImovelId");

                    b.HasIndex("TenantId", "ContribuinteId");

                    b.ToTable("Lancamentos", "tributos");
                });

            modelBuilder.Entity("Tensorroot.Gov.Modules.Tributos.Domain.Melhoria.ImovelBeneficiado", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("ContribuicaoRateada")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("ImovelId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ObraId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ProprietarioId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("ValorizacaoIndividual")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("ObraId");

                    b.ToTable("ImoveisBeneficiadosMelhoria", "tributos");
                });

            modelBuilder.Entity("Tensorroot.Gov.Modules.Tributos.Domain.Melhoria.ObraContribuicaoMelhoria", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("CustoTotalObra")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateOnly>("DataPublicacaoEdital")
                        .HasColumnType("date");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<decimal>("FatorAbsorcaoPercentual")
                        .HasColumnType("decimal(9,4)");

                    b.Property<DateOnly>("FimPrazoImpugnacao")
                        .HasColumnType("date");

                    b.Property<string>("FundamentoLegal")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("IdentificacaoObra")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("MemorialDescritivo")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<decimal>("ParcelaCustoFinanciadaPercentual")
                        .HasColumnType("decimal(9,4)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ZonaBeneficiada")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "IdentificacaoObra");

                    b.ToTable("ObrasContribuicaoMelhoria", "tributos");
                });

            modelBuilder.Entity("Tensorroot.Gov.Modules.Tributos.Domain.Nfse.NotaFiscalServico", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ChaveAcesso")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<int>("Competencia")
                        .HasColumnType("int");

                    b.Property<DateOnly>("DataEmissao")
                        .HasColumnType("date");

                    b.Property<bool>("IssRetidoNaFonte")
                        .HasColumnType("bit");

                    b.Property<string>("ItemListaServico")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("MunicipioIncidenciaIbge")
                        .HasMaxLength(7)
                        .HasColumnType("nvarchar(7)");

                    b.Property<string>("PrestadorCnpj")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("nvarchar(14)");

                    b.Property<string>("Situacao")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TomadorDocumento")
                        .HasMaxLength(14)
                        .HasColumnType("nvarchar(14)");

                    b.Property<decimal>("ValorIss")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ValorServico")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "ChaveAcesso")
                        .IsUnique();

                    b.HasIndex("TenantId", "PrestadorCnpj", "Competencia");

                    b.ToTable("NotasFiscaisServico", "tributos");
                });

            modelBuilder.Entity("Tensorroot.Gov.Modules.Tributos.Domain.Pgv.FaixaAliquotaIptu", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("AliquotaPercentual")
                        .HasColumnType("decimal(9,4)");

                    b.Property<Guid>("TabelaAliquotaIptuId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("ValorVenalMaximo")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ValorVenalMinimo")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("TabelaAliquotaIptuId");

                    b.ToTable("FaixasAliquotaIptu", "tributos");
                });

            modelBuilder.Entity("Tensorroot.Gov.Modules.Tributos.Domain.Pgv.FatorPgv", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Chave")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<decimal>("Multiplicador")
                        .HasColumnType("decimal(9,4)");

                    b.Property<Guid>("PlantaValoresId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.HasIndex("PlantaValoresId", "Tipo", "Chave")
                        .IsUnique();

                    b.ToTable("PgvFatores", "tributos");
                });

            modelBuilder.Entity("Tensorroot.Gov.Modules.Tributos.Domain.Pgv.PlantaValores", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Exercicio")
                        .HasColumnType("int");

                    b.Property<string>("FundamentoLegal")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Vigente")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "Exercicio");

                    b.ToTable("PlantasValores", "tributos");
                });

            modelBuilder.Entity("Tensorroot.Gov.Modules.Tributos.Domain.Pgv.TabelaAliquotaIptu", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Edificado")
                        .HasColumnType("bit");

                    b.Property<int>("Exercicio")
                        .HasColumnType("int");

                    b.Property<string>("FundamentoLegal")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Vigente")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "Exercicio", "Edificado");

                    b.ToTable("TabelasAliquotaIptu", "tributos");
                });

            modelBuilder.Entity("Tensorroot.Gov.Modules.Tributos.Domain.Pgv.ValorZona", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PlantaValoresId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("ValorM2Construcao")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ValorM2Terreno")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ZonaFiscal")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.HasKey("Id");

                    b.HasIndex("PlantaValoresId", "ZonaFiscal")
                        .IsUnique();

                    b.ToTable("PgvValoresZona", "tributos");
                });

            modelBuilder.Entity("Tensorroot.Gov.Modules.Tributos.Domain.Taxas.FaixaTaxa", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("LimiteInferior")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal?>("LimiteSuperior")
                        .HasColumnType("decimal(18,4)");

                    b.Property<Guid>("TabelaTaxaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Valor")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("TabelaTaxaId");

                    b.ToTable("FaixasTaxa", "tributos");
                });

            modelBuilder.Entity("Tensorroot.Gov.Modules.Tributos.Domain.Taxas.TabelaTaxa", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Especie")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<int>("Exercicio")
                        .HasColumnType("int");

                    b.Property<string>("FundamentoLegal")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("ModoCalculo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("ValorBase")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("Vigente")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "Codigo", "Exercicio");

                    b.ToTable("TabelasTaxa", "tributos");
                });

            modelBuilder.Entity("Tensorroot.Gov.SharedKernel.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("int");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DeadLetteredOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Error")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("NextAttemptUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("OccurredOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ProcessedOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("ProcessedOnUtc", "DeadLetteredOnUtc", "NextAttemptUtc");

                    b.ToTable("OutboxMessages", "tributos");
                });

            modelBuilder.Entity("Tensorroot.Gov.Modules.Tributos.Domain.Arrecadacao.Parcela", b =>
                {
                    b.HasOne("Tensorroot.Gov.Modules.Tributos.Domain.Arrecadacao.Dam", null)
                        .WithMany("Parcelas")
                        .HasForeignKey("DamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Tensorroot.Gov.Modules.Tributos.Domain.Cosip.FaixaCosip", b =>
                {
                    b.HasOne("Tensorroot.Gov.Modules.Tributos.Domain.Cosip.TabelaCosip", null)
                        .WithMany("Faixas")
                        .HasForeignKey("TabelaCosipId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Tensorroot.Gov.Modules.Tributos.Domain.Dividas.DividaAtiva", b =>
                {
                    b.OwnsOne("Tensorroot.Gov.Modules.Tributos.Domain.Dividas.RegraEncargosDivida", "RegraEncargos", b1 =>
                        {
                            b1.Property<Guid>("DividaAtivaId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<decimal>("CorrecaoPercentualMensal")
                                .HasColumnType("decimal(9,4)")
                                .HasColumnName("EncargosCorrecaoPercentualMensal");

                            b1.Property<string>("FundamentoLegal")
                                .IsRequired()
                                .HasMaxLength(300)
                                .HasColumnType("nvarchar(300)")
                                .HasColumnName("EncargosFundamentoLegal");

                            b1.Property<decimal>("JurosMoraPercentualMensal")
                                .HasColumnType("decimal(9,4)")
                                .HasColumnName("EncargosJurosMoraPercentualMensal");

                            b1.Property<decimal>("MultaMoraPercentual")
                                .HasColumnType("decimal(9,4)")
                                .HasColumnName("EncargosMultaMoraPercentual");

                            b1.HasKey("DividaAtivaId");

                            b1.ToTable("DividasAtivas", "tributos");

                            b1.WithOwner()
                                .HasForeignKey("DividaAtivaId");
                        });

                    b.Navigation("RegraEncargos")
                        .IsRequired();
                });

            modelBuilder.Entity("Tensorroot.Gov.Modules.Tributos.Domain.Dividas.RemessaProtesto", b =>
                {
                    b.HasOne("Tensorroot.Gov.Modules.Tributos.Domain.Dividas.DividaAtiva", null)
                        .WithMany("RemessasProtesto")
                        .HasForeignKey("DividaAtivaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Tensorroot.Gov.Modules.Tributos.Domain.Imoveis.Imovel", b =>
                {
                    b.OwnsOne("Tensorroot.Gov.Modules.Tributos.Domain.Imoveis.CaracteristicasImovel", "Caracteristicas", b1 =>
                        {
                            b1.Property<Guid>("ImovelId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<int?>("AnoConstrucao")
                                .HasColumnType("int")
                                .HasColumnName("AnoConstrucao");

                            b1.Property<decimal>("AreaConstruida")
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("AreaConstruida");

                            b1.Property<decimal>("AreaTerreno")
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("AreaTerreno");

                            b1.Property<decimal>("FracaoIdeal")
                                .HasColumnType("decimal(9,6)")
                                .HasColumnName("FracaoIdeal");

                            b1.Property<string>("PadraoConstrutivo")
                                .IsRequired()
                                .HasMaxLength(30)
                                .HasColumnType("nvarchar(30)")
                                .HasColumnName("PadraoConstrutivo");

                            b1.Property<string>("TipoUso")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("nvarchar(20)")
                                .HasColumnName("TipoUso");

                            b1.HasKey("ImovelId");

                            b1.ToTable("Imoveis", "tributos");

                            b1.WithOwner()
                                .HasForeignKey("ImovelId");
                        });

                    b.OwnsOne("Tensorroot.Gov.Modules.Tributos.Domain.Imoveis.EnderecoImovel", "Endereco", b1 =>
                        {
                            b1.Property<Guid>("ImovelId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Bairro")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("Bairro");

                            b1.Property<string>("Cep")
                                .HasMaxLength(8)
                                .HasColumnType("nvarchar(8)")
                                .HasColumnName("Cep");

                            b1.Property<string>("Complemento")
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("Complemento");

                            b1.Property<string>("FaceQuadra")
                                .HasMaxLength(60)
                                .HasColumnType("nvarchar(60)")
                                .HasColumnName("FaceQuadra");

                            b1.Property<string>("Logradouro")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("nvarchar(200)")
                                .HasColumnName("Logradouro");

                            b1.Property<string>("Numero")
                                .HasMaxLength(20)
                                .HasColumnType("nvarchar(20)")
                                .HasColumnName("Numero");

                            b1.Property<string>("SetorQuadraLote")
                                .IsRequired()
                                .HasMaxLength(60)
                                .HasColumnType("nvarchar(60)")
                                .HasColumnName("SetorQuadraLote");

                            b1.Property<string>("ZonaFiscal")
                                .IsRequired()
                                .HasMaxLength(60)
                                .HasColumnType("nvarchar(60)")
                                .HasColumnName("ZonaFiscal");

                            b1.HasKey("ImovelId");

                            b1.ToTable("Imoveis", "tributos");

                            b1.WithOwner()
                                .HasForeignKey("ImovelId");
                        });

                    b.OwnsOne("Tensorroot.Gov.Modules.Tributos.Domain.Imoveis.IdentificacaoImovel", "Identificacao", b1 =>
                        {
                            b1.Property<Guid>("ImovelId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("CibCodigo")
                                .HasMaxLength(20)
                                .HasColumnType("nvarchar(20)")
                                .HasColumnName("CibCodigo");

                            b1.Property<string>("InscricaoMunicipal")
                                .IsRequired()
                                .HasMaxLength(40)
                                .HasColumnType("nvarchar(40)")
                                .HasColumnName("InscricaoMunicipal");

                            b1.Property<string>("MatriculaRgi")
                                .HasMaxLength(40)
                                .HasColumnType("nvarchar(40)")
                                .HasColumnName("MatriculaRgi");

                            b1.HasKey("ImovelId");

                            b1.HasIndex("InscricaoMunicipal");

                            b1.ToTable("Imoveis", "tributos");

                            b1.WithOwner()
                                .HasForeignKey("ImovelId");
                        });

                    b.Navigation("Caracteristicas")
                        .IsRequired();

                    b.Navigation("Endereco")
                        .IsRequired();

                    b.Navigation("Identificacao")
                        .IsRequired();
                });

            modelBuilder.Entity("Tensorroot.Gov.Modules.Tributos.Domain.Iss.ItemAliquotaIss", b =>
                {
                    b.HasOne("Tensorroot.Gov.Modules.Tributos.Domain.Iss.TabelaAliquotaIss", null)
                        .WithMany("Itens")
                        .HasForeignKey("TabelaAliquotaIssId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Tensorroot.Gov.Modules.Tributos.Domain.Iss.ItemApuracaoIss", b =>
                {
                    b.HasOne("Tensorroot.Gov.Modules.Tributos.Domain.Iss.ApuracaoIss", null)
                        .WithMany("Itens")
                        .HasForeignKey("ApuracaoIssId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Tensorroot.Gov.Modules.Tributos.Domain.Melhoria.ImovelBeneficiado", b =>
                {
                    b.HasOne("Tensorroot.Gov.Modules.Tributos.Domain.Melhoria.ObraContribuicaoMelhoria", null)
                        .WithMany("Imoveis")
                        .HasForeignKey("ObraId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Tensorroot.Gov.Modules.Tributos.Domain.Pgv.FaixaAliquotaIptu", b =>
                {
                    b.HasOne("Tensorroot.Gov.Modules.Tributos.Domain.Pgv.TabelaAliquotaIptu", null)
                        .WithMany("Faixas")
                        .HasForeignKey("TabelaAliquotaIptuId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Tensorroot.Gov.Modules.Tributos.Domain.Pgv.FatorPgv", b =>
                {
                    b.HasOne("Tensorroot.Gov.Modules.Tributos.Domain.Pgv.PlantaValores", null)
                        .WithMany("Fatores")
                        .HasForeignKey("PlantaValoresId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Tensorroot.Gov.Modules.Tributos.Domain.Pgv.ValorZona", b =>
                {
                    b.HasOne("Tensorroot.Gov.Modules.Tributos.Domain.Pgv.PlantaValores", null)
                        .WithMany("Zonas")
                        .HasForeignKey("PlantaValoresId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Tensorroot.Gov.Modules.Tributos.Domain.Taxas.FaixaTaxa", b =>
                {
                    b.HasOne("Tensorroot.Gov.Modules.Tributos.Domain.Taxas.TabelaTaxa", null)
                        .WithMany("Faixas")
                        .HasForeignKey("TabelaTaxaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Tensorroot.Gov.Modules.Tributos.Domain.Arrecadacao.Dam", b =>
                {
                    b.Navigation("Parcelas");
                });

            modelBuilder.Entity("Tensorroot.Gov.Modules.Tributos.Domain.Cosip.TabelaCosip", b =>
                {
                    b.Navigation("Faixas");
                });

            modelBuilder.Entity("Tensorroot.Gov.Modules.Tributos.Domain.Dividas.DividaAtiva", b =>
                {
                    b.Navigation("RemessasProtesto");
                });

            modelBuilder.Entity("Tensorroot.Gov.Modules.Tributos.Domain.Iss.ApuracaoIss", b =>
                {
                    b.Navigation("Itens");
                });

            modelBuilder.Entity("Tensorroot.Gov.Modules.Tributos.Domain.Iss.TabelaAliquotaIss", b =>
                {
                    b.Navigation("Itens");
                });

            modelBuilder.Entity("Tensorroot.Gov.Modules.Tributos.Domain.Melhoria.ObraContribuicaoMelhoria", b =>
                {
                    b.Navigation("Imoveis");
                });

            modelBuilder.Entity("Tensorroot.Gov.Modules.Tributos.Domain.Pgv.PlantaValores", b =>
                {
                    b.Navigation("Fatores");

                    b.Navigation("Zonas");
                });

            modelBuilder.Entity("Tensorroot.Gov.Modules.Tributos.Domain.Pgv.TabelaAliquotaIptu", b =>
                {
                    b.Navigation("Faixas");
                });

            modelBuilder.Entity("Tensorroot.Gov.Modules.Tributos.Domain.Taxas.TabelaTaxa", b =>
                {
                    b.Navigation("Faixas");
                });
#pragma warning restore 612, 618
        }
    }
}
