// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Tensorroot.Gov.Modules.Protocolo.Infrastructure.Persistence;

#nullable disable

namespace Tensorroot.Gov.Modules.Protocolo.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ProtocoloDbContext))]
    [Migration("20260624052556_AddProtocoloW94TemporalidadeCarimboNup")]
    partial class AddProtocoloW94TemporalidadeCarimboNup
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("protocolo")
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Tensorroot.Gov.BuildingBlocks.Infrastructure.Auditing.AuditTrail", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("AffectedColumns")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EntityId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EntityName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("HashAnterior")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("HashAtual")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("IpAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NewValues")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OldValues")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("Sequencia")
                        .HasColumnType("bigint");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("TimestampUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "Sequencia")
                        .IsUnique()
                        .HasFilter("[Sequencia] > 0");

                    b.HasIndex("TenantId", "TimestampUtc");

                    b.ToTable("AuditTrail", "protocolo");
                });

            modelBuilder.Entity("Tensorroot.Gov.Modules.Protocolo.Domain.Arquivistica.DestinacaoProcesso", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("AutorizadoPor")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CodigoClassificacao")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<DateOnly?>("DataAptidaoEliminacao")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("DataEliminacao")
                        .HasColumnType("date");

                    b.Property<string>("DestinacaoFinal")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("EditalEliminacaoRef")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateOnly>("FimGuardaCorrente")
                        .HasColumnType("date");

                    b.Property<DateOnly>("FimGuardaIntermediaria")
                        .HasColumnType("date");

                    b.Property<Guid>("ProcessoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TermoEliminacaoHash")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "Estado");

                    b.HasIndex("TenantId", "ProcessoId")
                        .IsUnique();

                    b.ToTable("DestinacoesProcesso", "protocolo");
                });

            modelBuilder.Entity("Tensorroot.Gov.Modules.Protocolo.Domain.Arquivistica.PlanoDeClassificacao", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "Ativo");

                    b.ToTable("PlanosClassificacao", "protocolo");
                });

            modelBuilder.Entity("Tensorroot.Gov.Modules.Protocolo.Domain.Arquivistica.TabelaTemporalidade", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Ativa")
                        .HasColumnType("bit");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "Ativa");

                    b.ToTable("TabelasTemporalidade", "protocolo");
                });

            modelBuilder.Entity("Tensorroot.Gov.Modules.Protocolo.Domain.Documentos.Documento", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Criticidade")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateOnly?>("DataJuntada")
                        .HasColumnType("date");

                    b.Property<bool>("FormatoPdfA")
                        .HasColumnType("bit");

                    b.Property<string>("Hash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("MotivoSemEfeito")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("NivelAcesso")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<Guid?>("ProcessoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("SignatarioId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Situacao")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TipoAssinatura")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "ProcessoId");

                    b.ToTable("Documentos", "protocolo");
                });

            modelBuilder.Entity("Tensorroot.Gov.Modules.Protocolo.Domain.Processos.Processo", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Classificacao")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<DateOnly>("DataAutuacao")
                        .HasColumnType("date");

                    b.Property<string>("InteressadoDocumento")
                        .HasMaxLength(14)
                        .HasColumnType("nvarchar(14)");

                    b.Property<string>("NivelAcesso")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Nup")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<Guid?>("OrigemId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("OrigemModulo")
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<Guid?>("RequerimentoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("SetorAtualId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Situacao")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.ComplexProperty<Dictionary<string, object>>("Prazo", "Tensorroot.Gov.Modules.Protocolo.Domain.Processos.Processo.Prazo#Prazo", b1 =>
                        {
                            b1.Property<DateOnly>("Fim")
                                .HasColumnType("date")
                                .HasColumnName("PrazoFim");

                            b1.Property<DateOnly>("Inicio")
                                .HasColumnType("date")
                                .HasColumnName("PrazoInicio");
                        });

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "InteressadoDocumento");

                    b.HasIndex("TenantId", "Nup")
                        .IsUnique();

                    b.HasIndex("TenantId", "SetorAtualId");

                    b.ToTable("Processos", "protocolo");
                });

            modelBuilder.Entity("Tensorroot.Gov.Modules.Protocolo.Domain.Processos.SequenciaNup", b =>
                {
                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Ano")
                        .HasColumnType("int");

                    b.Property<int>("UltimoSequencial")
                        .HasColumnType("int");

                    b.HasKey("TenantId", "Ano");

                    b.ToTable("SequenciasNup", "protocolo");
                });

            modelBuilder.Entity("Tensorroot.Gov.SharedKernel.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("int");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DeadLetteredOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Error")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("NextAttemptUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("OccurredOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ProcessedOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("ProcessedOnUtc", "DeadLetteredOnUtc", "NextAttemptUtc");

                    b.ToTable("OutboxMessages", "protocolo");
                });

            modelBuilder.Entity("Tensorroot.Gov.Modules.Protocolo.Domain.Arquivistica.PlanoDeClassificacao", b =>
                {
                    b.OwnsMany("Tensorroot.Gov.Modules.Protocolo.Domain.Arquivistica.ClasseDocumental", "Classes", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Assunto")
                                .IsRequired()
                                .HasMaxLength(300)
                                .HasColumnType("nvarchar(300)");

                            b1.Property<string>("Atividade")
                                .IsRequired()
                                .HasMaxLength(10)
                                .HasColumnType("nvarchar(10)");

                            b1.Property<string>("CodigoClassificacao")
                                .IsRequired()
                                .HasMaxLength(60)
                                .HasColumnType("nvarchar(60)");

                            b1.Property<string>("CodigoPai")
                                .HasMaxLength(60)
                                .HasColumnType("nvarchar(60)");

                            b1.Property<Guid>("PlanoDeClassificacaoId")
                                .HasColumnType("uniqueidentifier");

                            b1.HasKey("Id");

                            b1.HasIndex("PlanoDeClassificacaoId", "CodigoClassificacao");

                            b1.ToTable("ClassesDocumentais", "protocolo");

                            b1.WithOwner()
                                .HasForeignKey("PlanoDeClassificacaoId");
                        });

                    b.Navigation("Classes");
                });

            modelBuilder.Entity("Tensorroot.Gov.Modules.Protocolo.Domain.Arquivistica.TabelaTemporalidade", b =>
                {
                    b.OwnsMany("Tensorroot.Gov.Modules.Protocolo.Domain.Arquivistica.RegraTemporalidade", "Regras", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("CodigoClassificacao")
                                .IsRequired()
                                .HasMaxLength(60)
                                .HasColumnType("nvarchar(60)");

                            b1.Property<string>("DestinacaoFinal")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("nvarchar(20)");

                            b1.Property<string>("EventoContagem")
                                .IsRequired()
                                .HasMaxLength(30)
                                .HasColumnType("nvarchar(30)");

                            b1.Property<string>("Observacao")
                                .HasMaxLength(500)
                                .HasColumnType("nvarchar(500)");

                            b1.Property<int>("PrazoGuardaCorrenteAnos")
                                .HasColumnType("int");

                            b1.Property<int>("PrazoGuardaIntermediariaAnos")
                                .HasColumnType("int");

                            b1.Property<Guid>("TabelaTemporalidadeId")
                                .HasColumnType("uniqueidentifier");

                            b1.HasKey("Id");

                            b1.HasIndex("TabelaTemporalidadeId", "CodigoClassificacao");

                            b1.ToTable("RegrasTemporalidade", "protocolo");

                            b1.WithOwner()
                                .HasForeignKey("TabelaTemporalidadeId");
                        });

                    b.Navigation("Regras");
                });

            modelBuilder.Entity("Tensorroot.Gov.Modules.Protocolo.Domain.Documentos.Documento", b =>
                {
                    b.OwnsOne("Tensorroot.Gov.Modules.Protocolo.Domain.ValueObjects.CarimboDeTempo", "CarimboTempo", b1 =>
                        {
                            b1.Property<Guid>("DocumentoId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("AlgoritmoHash")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("nvarchar(20)")
                                .HasColumnName("CarimboAlgoritmo");

                            b1.Property<string>("Autoridade")
                                .IsRequired()
                                .HasMaxLength(120)
                                .HasColumnType("nvarchar(120)")
                                .HasColumnName("CarimboAutoridade");

                            b1.Property<string>("HashCarimbado")
                                .HasMaxLength(64)
                                .HasColumnType("nvarchar(64)")
                                .HasColumnName("CarimboHashCarimbado");

                            b1.Property<DateTime>("InstanteUtc")
                                .HasColumnType("datetime2")
                                .HasColumnName("CarimboInstanteUtc");

                            b1.Property<string>("Origem")
                                .IsRequired()
                                .HasMaxLength(10)
                                .HasColumnType("nvarchar(10)")
                                .HasColumnName("CarimboOrigem");

                            b1.Property<string>("PoliticaCarimbo")
                                .HasMaxLength(64)
                                .HasColumnType("nvarchar(64)")
                                .HasColumnName("CarimboPolitica");

                            b1.Property<string>("SerialToken")
                                .HasMaxLength(128)
                                .HasColumnType("nvarchar(128)")
                                .HasColumnName("CarimboSerial");

                            b1.Property<string>("TokenBase64")
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("CarimboTokenBase64");

                            b1.HasKey("DocumentoId");

                            b1.ToTable("Documentos", "protocolo");

                            b1.WithOwner()
                                .HasForeignKey("DocumentoId");
                        });

                    b.Navigation("CarimboTempo");
                });

            modelBuilder.Entity("Tensorroot.Gov.Modules.Protocolo.Domain.Processos.Processo", b =>
                {
                    b.OwnsMany("Tensorroot.Gov.Modules.Protocolo.Domain.Processos.Despacho", "Despachos", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<Guid>("AutoridadeId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<DateOnly>("DataDespacho")
                                .HasColumnType("date");

                            b1.Property<Guid>("ProcessoId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Texto")
                                .IsRequired()
                                .HasMaxLength(4000)
                                .HasColumnType("nvarchar(4000)");

                            b1.HasKey("Id");

                            b1.HasIndex("ProcessoId");

                            b1.ToTable("ProcessosDespachos", "protocolo");

                            b1.WithOwner()
                                .HasForeignKey("ProcessoId");
                        });

                    b.OwnsMany("Tensorroot.Gov.Modules.Protocolo.Domain.Processos.Movimentacao", "Movimentacoes", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<DateOnly>("DataMovimentacao")
                                .HasColumnType("date");

                            b1.Property<string>("Observacao")
                                .HasMaxLength(2000)
                                .HasColumnType("nvarchar(2000)");

                            b1.Property<Guid>("ProcessoId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<Guid>("SetorDestinoId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<Guid?>("SetorOrigemId")
                                .HasColumnType("uniqueidentifier");

                            b1.HasKey("Id");

                            b1.HasIndex("ProcessoId");

                            b1.ToTable("ProcessosMovimentacoes", "protocolo");

                            b1.WithOwner()
                                .HasForeignKey("ProcessoId");
                        });

                    b.Navigation("Despachos");

                    b.Navigation("Movimentacoes");
                });
#pragma warning restore 612, 618
        }
    }
}
